const sb=window.shubhSupabase;let user=null,provider=null;
function msg(t){document.getElementById('msg').textContent=t}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function login(){const r=await sb.auth.signInWithPassword({email:email.value.trim(),password:password.value});if(r.error)return msg(r.error.message);user=r.data.user;await load()}
async function register(){if(password.value.length<8)return msg('Password 8+ characters rakhein.');const r=await sb.auth.signUp({email:email.value.trim(),password:password.value});if(r.error)return msg(r.error.message);user=r.data.user;if(!user)return msg('Email verification ke baad login kijiye.');const p=await sb.from('service_providers').upsert({user_id:user.id,name:name.value.trim(),phone:phone.value.trim(),email:email.value.trim(),business_name:name.value.trim(),category:category.value.trim(),service_area:area.value.trim(),status:'Pending',kyc_status:'Pending'},{onConflict:'user_id'});if(p.error)return msg(p.error.message);await load()}
async function load(){const p=await sb.from('service_providers').select('*').eq('user_id',user.id).maybeSingle();if(p.error)return msg(p.error.message);provider=p.data;if(!provider)return msg('Provider profile nahi mila. Register kijiye.');document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('profile').textContent=esc(provider.business_name)+' · '+esc(provider.status)+' · KYC '+esc(provider.kyc_status);loadServices();loadBookings()}
async function addService(){if(!provider)return;const r=await sb.from('services').insert({provider_id:provider.id,name:sname.value.trim(),category:scat.value.trim(),description:sdesc.value.trim(),price:Number(sprice.value),duration_minutes:Number(sduration.value||60),service_area:sarea.value.trim(),image_url:simage.value.trim(),status:'Pending'});if(r.error)return msg(r.error.message);msg('Service approval ke liye submit ho gayi.');loadServices()}
async function loadServices(){const r=await sb.from('services').select('id,name,category,price,status,duration_minutes').eq('provider_id',provider.id).order('created_at',{ascending:false});document.getElementById('services').innerHTML=r.data?.map(s=>'<div class="card"><b>'+esc(s.name)+'</b> · '+esc(s.category)+' · ₹'+Number(s.price).toFixed(0)+' · '+esc(s.status)+'<br>Duration '+Number(s.duration_minutes)+' min</div>').join('')||'No services.'}
async function loadBookings(){const r=await sb.from('service_bookings').select('id,booking_status,total_amount,address,created_at,services(name)').eq('provider_id',provider.id).order('created_at',{ascending:false});document.getElementById('bookings').innerHTML=r.data?.map(b=>'<div class="card"><b>'+esc(b.services?.name||'Service')+'</b> · ₹'+Number(b.total_amount).toFixed(0)+'<br>'+esc(b.booking_status)+' · '+esc(b.address||'')+'<br><button class="btn" onclick="status(\\''+b.id+'\\',\\'Provider Accepted\\')">Accept</button><button class="btn alt" onclick="status(\\''+b.id+'\\',\\'Rejected\\')">Reject</button><button class="btn" onclick="status(\\''+b.id+'\\',\\'Completed\\')">Complete</button></div>').join('')||'No bookings.'}
async function status(id,v){const r=await sb.rpc('update_service_booking_status',{p_booking_id:id,p_status:v,p_note:'Provider updated booking'});if(r.error)return msg(r.error.message);loadBookings()}
async function logout(){await sb.auth.signOut();location.reload()}
sb.auth.getSession().then(r=>{user=r.data.session?.user||null;if(user)load()});