const sb=window.shubhSupabase;
let sellerUser=null,seller=null;
function note(t,bad){const e=document.getElementById("msg");e.className="msg "+(bad?"danger":"ok");e.textContent=t;}
function clean(v){return String(v||"").replace(/[&<>"']/g,"");}
async function sellerLogin(){const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value;if(!email||!password)return note("Email aur password bhariye.",true);const r=await sb.auth.signInWithPassword({email,password});if(r.error)return note(r.error.message,true);await bootSeller();}
async function sellerRegister(){const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value,name=document.getElementById("name").value.trim(),mobile=document.getElementById("mobile").value.trim(),shop=document.getElementById("shop").value.trim(),address=document.getElementById("address").value.trim(),gst=document.getElementById("gst").value.trim();if(!email||!password||!name||!mobile||!shop)return note("Name, mobile, shop, email aur password zaroor bhariye.",true);localStorage.setItem("shubhmart_seller_draft",JSON.stringify({name,mobile,shop,address,gst}));const r=await sb.auth.signUp({email,password});if(r.error)return note(r.error.message,true);if(r.data.user&&r.data.session)await finishSellerSetup(r.data.user);else note("Registration ho gaya. Email verify karke isi page par Login kijiye.");}
async function finishSellerSetup(user){const d=JSON.parse(localStorage.getItem("shubhmart_seller_draft")||"{}");let r=await sb.from("profiles").upsert({id:user.id,full_name:d.name||"",phone:d.mobile||"",role:"seller"},{onConflict:"id"});if(r.error)return note("Seller profile error: "+r.error.message,true);r=await sb.from("Sellers").upsert({user_id:user.id,seller_name:d.name||"",mobile:d.mobile||"",email:user.email||"",shop_name:d.shop||"",address:d.address||"",gst_number:d.gst||"",status:"Pending",kyc_status:"Pending"},{onConflict:"user_id"}).select().single();if(r.error)return note("Seller setup error: "+r.error.message,true);seller=r.data;sellerUser=user;localStorage.removeItem("shubhmart_seller_draft");showDashboard();}
async function bootSeller(){const r=await sb.auth.getUser();const user=r.data.user;if(!user)return;sellerUser=user;let q=await sb.from("Sellers").select("*").eq("user_id",user.id).maybeSingle();if(q.error)return note("Seller profile load error: "+q.error.message,true);if(!q.data){const d=JSON.parse(localStorage.getItem("shubhmart_seller_draft")||"{}");if(d.name)return finishSellerSetup(user);return note("Seller profile nahi mila. New Seller Registration kijiye.",true);}seller=q.data;showDashboard();}
function showDashboard(){document.getElementById("authPanel").classList.add("hidden");document.getElementById("dashboard").classList.remove("hidden");document.getElementById("logoutBtn").classList.remove("hidden");document.getElementById("sellerTitle").textContent=(seller.shop_name||seller.seller_name||"Seller")+" — Dashboard";document.getElementById("sellerStatus").textContent="Account: "+(seller.status||"Pending")+" | KYC: "+(seller.kyc_status||"Pending");document.getElementById("pSellerName").value=seller.seller_name||"";document.getElementById("pMobile").value=seller.mobile||"";document.getElementById("pShop").value=seller.shop_name||"";document.getElementById("pAddress").value=seller.address||"";document.getElementById("pPan").value=seller.pan||"";document.getElementById("pGst").value=seller.gst_number||"";loadMyProducts();loadMyOrders();}
async function saveSellerProfile(){const patch={seller_name:document.getElementById("pSellerName").value.trim(),mobile:document.getElementById("pMobile").value.trim(),shop_name:document.getElementById("pShop").value.trim(),address:document.getElementById("pAddress").value.trim(),pan:document.getElementById("pPan").value.trim(),gst_number:document.getElementById("pGst").value.trim()};const r=await sb.from("Sellers").update(patch).eq("id",seller.id).select().single();if(r.error)return note(r.error.message,true);seller=r.data;showDashboard();note("Shop profile saved.");}
async function addSellerProduct(){const name=document.getElementById("prodName").value.trim(),category=document.getElementById("prodCategory").value.trim(),price=Number(document.getElementById("prodPrice").value),mrp=Number(document.getElementById("prodMrp").value),stock=Math.max(0,Number(document.getElementById("prodStock").value||0)),image_url=document.getElementById("prodImage").value.trim(),description=document.getElementById("prodDescription").value.trim();if(!seller||!name||!category||!(price>0))return note("Seller profile, product name, category aur valid price bhariye.",true);const r=await sb.from("products").insert({name,category,price,mrp:mrp>0?mrp:null,stock,image_url,description,seller_id:seller.id,status:"Pending"});if(r.error)return note("Product add error: "+r.error.message,true);["prodName","prodCategory","prodPrice","prodMrp","prodStock","prodImage","prodDescription"].forEach(id=>document.getElementById(id).value="");await loadMyProducts();note("Product submit ho gaya. Status: Pending.");}
async function loadMyProducts(){const r=await sb.from("products").select("id,name,category,price,mrp,stock,image_url,status,created_at").eq("seller_id",seller.id).order("created_at",{ascending:false});const e=document.getElementById("myProducts");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data&&r.data.length?r.data.map(p=>"<div class='product'><b>"+clean(p.name)+"</b><div>₹"+Number(p.price||0).toFixed(2)+" | Stock: "+Number(p.stock||0)+"</div><div>Status: "+clean(p.status)+"</div></div>").join(""):"No products yet.";}
async function loadMyOrders(){const r=await sb.from("Orders").select("id,total_amount,order_status,payment_status,created_at").eq("seller_id",seller.id).order("created_at",{ascending:false}).limit(30);const e=document.getElementById("myOrders");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data&&r.data.length?r.data.map(o=>"<div class='panel'><b>Order "+clean(o.id.slice(0,8))+"…</b><br>₹"+Number(o.total_amount||0).toFixed(2)+" | "+clean(o.order_status)+" | Payment: "+clean(o.payment_status)+"</div>").join(""):"No seller orders yet.";}
async function sellerLogout(){await sb.auth.signOut();location.reload();}
sb.auth.onAuthStateChange((event,session)=>{if(session&&!sellerUser)setTimeout(bootSeller,0);});
bootSeller();