const sb=window.shubhSupabase;
let sellerUser=null,seller=null;
function note(t,bad){const e=document.getElementById("msg");e.className="msg "+(bad?"danger":"ok");e.textContent=t;}
function clean(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
async function sellerLogin(){const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value;if(!email||!password)return note("Email aur password bhariye.",true);const r=await sb.auth.signInWithPassword({email,password});if(r.error)return note(r.error.message,true);await bootSeller();}
async function sellerRegister(){const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value,name=document.getElementById("name").value.trim(),mobile=document.getElementById("mobile").value.trim(),shop=document.getElementById("shop").value.trim(),address=document.getElementById("address").value.trim(),gst=document.getElementById("gst").value.trim();if(!email||!password||!name||!mobile||!shop)return note("Name, mobile, shop, email aur password zaroor bhariye.",true);localStorage.setItem("shubhmart_seller_draft",JSON.stringify({name,mobile,shop,address,gst}));const r=await sb.auth.signUp({email,password});if(r.error)return note(r.error.message,true);if(r.data.user&&r.data.session)await finishSellerSetup(r.data.user);else note("Registration ho gaya. Email verify karke isi page par Login kijiye.");}
async function finishSellerSetup(user){const d=JSON.parse(localStorage.getItem("shubhmart_seller_draft")||"{}");let r=await sb.from("profiles").upsert({id:user.id,full_name:d.name||"",phone:d.mobile||"",role:"seller"},{onConflict:"id"});if(r.error)return note("Seller profile error: "+r.error.message,true);r=await sb.from("Sellers").upsert({user_id:user.id,seller_name:d.name||"",mobile:d.mobile||"",email:user.email||"",shop_name:d.shop||"",address:d.address||"",gst_number:d.gst||"",status:"Pending",kyc_status:"Pending"},{onConflict:"user_id"}).select().single();if(r.error)return note("Seller setup error: "+r.error.message,true);seller=r.data;sellerUser=user;localStorage.removeItem("shubhmart_seller_draft");showDashboard();}
async function bootSeller(){const r=await sb.auth.getUser();const user=r.data.user;if(!user)return;sellerUser=user;let q=await sb.from("Sellers").select("*").eq("user_id",user.id).maybeSingle();if(q.error)return note("Seller profile load error: "+q.error.message,true);if(!q.data){const d=JSON.parse(localStorage.getItem("shubhmart_seller_draft")||"{}");if(d.name)return finishSellerSetup(user);return note("Seller profile nahi mila. New Seller Registration kijiye.",true);}seller=q.data;showDashboard();}
function showDashboard(){document.getElementById("authPanel").classList.add("hidden");document.getElementById("dashboard").classList.remove("hidden");document.getElementById("logoutBtn").classList.remove("hidden");document.getElementById("sellerTitle").textContent=(seller.shop_name||seller.seller_name||"Seller")+" — Dashboard";document.getElementById("sellerStatus").textContent="Account: "+(seller.status||"Pending")+" | KYC: "+(seller.kyc_status||"Pending");document.getElementById("pSellerName").value=seller.seller_name||"";document.getElementById("pMobile").value=seller.mobile||"";document.getElementById("pShop").value=seller.shop_name||"";document.getElementById("pAddress").value=seller.address||"";document.getElementById("pPan").value=seller.pan||"";document.getElementById("pGst").value=seller.gst_number||"";loadMyProducts();loadMyOrders();loadKyc();loadSellerFinance();}
async function saveSellerProfile(){const patch={p_seller_id:seller.id,p_seller_name:document.getElementById("pSellerName").value.trim(),p_mobile:document.getElementById("pMobile").value.trim(),p_shop_name:document.getElementById("pShop").value.trim(),p_address:document.getElementById("pAddress").value.trim(),p_pan:document.getElementById("pPan").value.trim(),p_gst:document.getElementById("pGst").value.trim()};const r=await sb.rpc("update_seller_profile",patch);if(r.error)return note(r.error.message,true);seller={...seller,seller_name:patch.p_seller_name,mobile:patch.p_mobile,shop_name:patch.p_shop_name,address:patch.p_address,pan:patch.p_pan,gst_number:patch.p_gst};document.getElementById("sellerTitle").textContent=(seller.shop_name||seller.seller_name)+" — Dashboard";note("Shop profile securely saved.");}
async function addSellerProduct(){const name=document.getElementById("prodName").value.trim(),category=document.getElementById("prodCategory").value.trim(),price=Number(document.getElementById("prodPrice").value),mrp=Number(document.getElementById("prodMrp").value),stock=Math.max(0,Number(document.getElementById("prodStock").value||0)),image_url=document.getElementById("prodImage").value.trim(),description=document.getElementById("prodDescription").value.trim();if(!seller||!name||!category||!(price>0))return note("Seller profile, product name, category aur valid price bhariye.",true);const r=await sb.from("products").insert({name,category,price,mrp:mrp>0?mrp:null,stock,image_url,description,seller_id:seller.id,status:"Pending"}).select("id").single();if(r.error)return note("Product add error: "+r.error.message,true);const bulkMin=Math.floor(Number(document.getElementById("bulkMin").value||0)),bulkMax=Math.floor(Number(document.getElementById("bulkMax").value||0)),bulkPrice=Number(document.getElementById("bulkPrice").value||0);if(bulkMin>1&&bulkPrice>0){if(bulkMax&&bulkMax<bulkMin)return note("Bulk max quantity, min quantity se kam nahi ho sakti.",true);const wr=await sb.from("wholesale_pricing").insert({product_id:r.data.id,seller_id:seller.id,min_quantity:bulkMin,max_quantity:bulkMax||null,unit_price:bulkPrice,status:"Pending"});if(wr.error)return note("Bulk pricing error: "+wr.error.message,true);}["prodName","prodCategory","prodPrice","prodMrp","prodStock","prodImage","prodDescription","bulkMin","bulkMax","bulkPrice"].forEach(id=>document.getElementById(id).value="");await loadMyProducts();note("Product submit ho gaya. Status: Pending.");}
async function addSellerVariant(){if(!seller)return;const productId=document.getElementById("variantProductId").value.trim(),sku=document.getElementById("variantSku").value.trim(),variantName=document.getElementById("variantName").value.trim(),optionValue=document.getElementById("variantValue").value.trim(),price=Number(document.getElementById("variantPrice").value),mrp=Number(document.getElementById("variantMrp").value),stock=Math.floor(Number(document.getElementById("variantStock").value||0)),image_url=document.getElementById("variantImage").value.trim();if(!productId||!variantName||!optionValue||!(price>0)||!(mrp>=price)||stock<0)return note("Variant details aur valid price/MRP/stock bhariye.",true);const r=await sb.rpc("seller_add_product_variant",{p_product_id:productId,p_sku:sku||null,p_variant_name:variantName,p_option_value:optionValue,p_price:price,p_mrp:mrp,p_stock:stock,p_image_url:image_url||null});if(r.error)return note("Variant add error: "+r.error.message,true);note("Variant Pending approval ke liye save ho gaya.");loadSellerVariants(productId);}
async function loadSellerVariants(productId){const e=document.getElementById("sellerVariants");if(!productId)return;e.textContent="Loading…";const r=await sb.from("product_variants").select("id,sku,variant_name,option_value,price,mrp,stock,status").eq("product_id",productId).order("created_at",{ascending:false});if(r.error)return e.textContent=r.error.message;e.innerHTML=(r.data||[]).map(v=>"<div class='product'><b>"+clean(v.variant_name)+"</b>: "+clean(v.option_value)+" | SKU "+clean(v.sku||"-")+" | ₹"+Number(v.price||0).toFixed(2)+" | Stock "+Number(v.stock||0)+" | "+clean(v.status)+"</div>").join("")||"No variants yet.";}
async function updateBulkStock(){const id=document.getElementById("bulkStockProductId").value.trim(),v=Math.floor(Number(document.getElementById("bulkStockValue").value));if(!id||!Number.isInteger(v)||v<0)return note("Product ID aur valid stock bhariye.",true);const r=await sb.rpc("update_seller_product_stock",{p_product_id:id,p_stock:v});if(r.error)return note(r.error.message,true);document.getElementById("bulkStockMsg").textContent="Stock updated securely.";loadMyProducts();}
async function loadMyProducts(){const r=await sb.from("products").select("id,name,category,price,mrp,stock,image_url,status,created_at").eq("seller_id",seller.id).order("created_at",{ascending:false});const e=document.getElementById("myProducts");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data&&r.data.length?r.data.map(p=>"<div class='product'><b>"+clean(p.name)+"</b><div>₹"+Number(p.price||0).toFixed(2)+" | Stock: "+Number(p.stock||0)+" | "+clean(p.status)+"</div><input id='stock_"+p.id+"' type='number' min='0' value='"+Number(p.stock||0)+"'><button class='btn alt' onclick="updateSellerStock('"+p.id+"')">Save Stock</button><button class='btn alt' onclick="editSellerProduct('"+p.id+"')">Edit</button></div>").join(""):"No products yet.";}
async function updateSellerStock(id){const v=Math.floor(Number(document.getElementById("stock_"+id)?.value));if(!Number.isInteger(v)||v<0)return note("Valid stock bhariye.",true);const r=await sb.rpc("update_seller_product_stock",{p_product_id:id,p_stock:v});if(r.error)return note(r.error.message,true);await loadMyProducts();note("Stock securely updated.");}
async function submitSellerKyc(){if(!seller)return;const t=document.getElementById("kycType").value.trim(),n=document.getElementById("kycNumber").value.trim(),u=document.getElementById("kycUrl").value.trim();const r=await sb.rpc("submit_seller_kyc",{p_seller_id:seller.id,p_document_type:t,p_document_number:n,p_document_url:u||null});if(r.error)return note(r.error.message,true);document.getElementById("kycStatus").textContent="KYC status: Pending admin review";seller.kyc_status="Pending";document.getElementById("sellerStatus").textContent="Account: "+(seller.status||"Pending")+" | KYC: Pending";note("KYC securely submitted for admin review.");}
async function loadKyc(){const r=await sb.from("seller_kyc").select("document_type,status,rejection_reason,created_at").eq("seller_id",seller.id).order("created_at",{ascending:false}).limit(1).maybeSingle();const e=document.getElementById("kycStatus");if(r.error)return e.textContent=r.error.message;if(!r.data)return e.textContent="KYC: Not submitted";e.textContent="KYC: "+r.data.status+" | "+clean(r.data.document_type)+(r.data.rejection_reason?" | "+clean(r.data.rejection_reason):"");}
async function loadMyOrders(){const r=await sb.from("Orders").select("id,total_amount,order_status,payment_status,created_at").eq("seller_id",seller.id).order("created_at",{ascending:false}).limit(30);const e=document.getElementById("myOrders");if(r.error)return e.textContent=r.error.message;if(!r.data?.length)return e.textContent="No seller orders yet.";const ids=r.data.map(o=>o.id);const sh=ids.length?await sb.from("shipments").select("order_id,tracking_number,shipment_status,estimated_delivery_at").in("order_id",ids):{data:[]};const map=Object.fromEntries((sh.data||[]).map(x=>[x.order_id,x]));e.innerHTML=r.data.map(o=>{const s=map[o.id];const actions=["Pending","Confirmed","Processing","Packed"].includes(o.order_status)?["Confirmed","Processing","Packed","Dispatched","Cancelled"].map(st=>"<button class='btn alt' onclick="updateSellerOrderStatus('"+o.id+"','"+st+"')">"+st+"</button>").join(""):"";return "<div class='panel'><b>Order "+clean(o.id.slice(0,8))+"…</b><br>₹"+Number(o.total_amount||0).toFixed(2)+" | "+clean(o.order_status)+" | Payment: "+clean(o.payment_status)+"<br>🚚 "+clean(s?.shipment_status||"Shipment pending")+(s?.tracking_number?" | "+clean(s.tracking_number):"")+"<div>"+actions+"</div></div>"}).join("");}
async function updateSellerOrderStatus(id,status){if(!confirm("Order status '"+status+"' set karein?"))return;const r=await sb.rpc("update_seller_order_status",{p_order_id:id,p_status:status});if(r.error)return note(r.error.message,true);await loadMyOrders();note("Order status updated securely.");}
async function requestSellerPayout(){const amount=Number(prompt("Kitna payout request karna hai?"));if(!(amount>0))return note("Valid payout amount bhariye.",true);const r=await sb.rpc("request_seller_payout",{p_amount:amount});if(r.error)return note(r.error.message,true);await loadSellerFinance();note("Payout request Pending mein save ho gayi.");}\nasync function loadSellerFinance(){const e=document.getElementById("sellerFinance");const [c,p]=await Promise.all([sb.from("commissions").select("gross_amount,commission_amount,seller_earning,status,created_at").eq("seller_id",seller.id).order("created_at",{ascending:false}).limit(50),sb.from("payouts").select("amount,status,payout_reference,requested_at,paid_at").eq("seller_id",seller.id).order("requested_at",{ascending:false}).limit(20)]);if(c.error||p.error)return e.textContent=(c.error||p.error).message;const earn=(c.data||[]).reduce((a,x)=>a+Number(x.seller_earning||0),0),comm=(c.data||[]).reduce((a,x)=>a+Number(x.commission_amount||0),0);e.innerHTML="<b>Seller earnings:</b> ₹"+earn.toFixed(2)+"<br><b>Commission:</b> ₹"+comm.toFixed(2)+"<br><b>Commission records:</b> "+(c.data||[]).length+"<br><button class="btn" onclick="requestSellerPayout()">Request Payout</button><hr><b>Recent payouts:</b><br>"+((p.data||[]).map(x=>"₹"+Number(x.amount||0).toFixed(2)+" — "+clean(x.status)+" — "+clean(x.payout_reference||"")).join("<br>")||"No payouts yet.");}
async function sellerLogout(){await sb.auth.signOut();location.reload();}
sb.auth.onAuthStateChange((event,session)=>{if(session&&!sellerUser)setTimeout(bootSeller,0);});
bootSeller();
async function generateAIListing(){const input=document.getElementById("aiListingInput")?.value.trim();if(!input)return note("Product details likhiye.",true);const box=document.getElementById("aiListingResult");box.textContent="AI draft bana raha hai…";try{const r=await shubhAI("listing",{input});box.innerHTML='<div class="panel"><b>Title</b><input id="aiTitle" value="'+clean(r.title)+'"><b>Description</b><textarea id="aiDesc">'+clean(r.description)+'</textarea><b>Category</b><input id="aiCategory" value="'+clean(r.category)+'"><div>Quality score: <b>'+Number(r.quality_score||0)+'/100</b></div><div class="small">Keywords: '+clean((r.keywords||[]).join(", "))+'</div><button class="btn" onclick="useAIListing()">Use in Product Form</button><button class="btn alt" onclick="saveAIDraft()">Save Draft</button></div>';window._aiListing=r;}catch(e){box.textContent="AI service error: "+e.message;}}
function useAIListing(){const r=window._aiListing||{};document.getElementById("prodName").value=r.title||"";document.getElementById("prodCategory").value=r.category||"";document.getElementById("prodDescription").value=r.description||"";note("AI draft product form mein aa gaya. Price/stock check karke submit kijiye.");}
async function saveAIDraft(){if(!seller||!window._aiListing)return;const x=await sb.from("ai_listing_drafts").insert({seller_id:seller.id,input_text:document.getElementById("aiListingInput").value.trim(),output:window._aiListing,status:"Draft"});if(x.error)return note("AI draft save error: "+x.error.message,true);note("AI draft secure seller history mein save ho gaya.");}

async function loadSellerReturns(){
 const e=document.getElementById("sellerReturns"); if(!e||!seller)return;
 const r=await sb.from("returns").select("id,order_id,status,return_type,reason_code,refund_amount,refund_status,pickup_status,requested_at,decision_at").order("requested_at",{ascending:false}).limit(50);
 if(r.error){e.textContent=r.error.message;return;}
 e.innerHTML=(r.data||[]).map(x=>"<div class='product'><b>Return "+clean(x.id.slice(0,8))+"…</b><br>Order: "+clean(x.order_id.slice(0,8))+"… | "+clean(x.return_type)+" | "+clean(x.status)+"<br>Reason: "+clean(x.reason_code||"-")+" | Refund: ₹"+Number(x.refund_amount||0).toFixed(2)+" ("+clean(x.refund_status||"-")+")<br>Pickup: "+clean(x.pickup_status||"-")+"</div>").join("")||"No return/RTO requests yet.";
}
async function loadSellerOffers(){
 const e=document.getElementById("sellerOffers"); if(!e||!seller)return;
 const r=await sb.from("product_offers").select("id,product_id,code,title,discount_type,discount_value,min_order_amount,max_discount,starts_at,ends_at,status").eq("seller_id",seller.id).order("created_at",{ascending:false}).limit(50);
 if(r.error){e.textContent=r.error.message;return;}
 e.innerHTML=(r.data||[]).map(x=>"<div class='product'><b>"+clean(x.title)+"</b> — "+clean(x.code)+"<br>Product: "+clean(x.product_id)+" | "+clean(x.discount_type)+" "+Number(x.discount_value||0)+" | Min ₹"+Number(x.min_order_amount||0).toFixed(2)+" | "+clean(x.status)+"<br><button class='btn alt' onclick=\"cancelSellerOffer('"+x.id+"')\">Cancel Offer</button></div>").join("")||"No offers yet.";
}
async function addSellerOffer(){
 const productId=document.getElementById("offerProductId").value.trim(),code=document.getElementById("offerCode").value.trim(),title=document.getElementById("offerTitle").value.trim(),type=document.getElementById("offerType").value,discount=Number(document.getElementById("offerDiscount").value),min=Number(document.getElementById("offerMin").value||0),maxRaw=document.getElementById("offerMax").value, max=maxRaw===""?null:Number(maxRaw),start=document.getElementById("offerStart").value,endRaw=document.getElementById("offerEnd").value,end=endRaw?new Date(endRaw).toISOString():null;
 if(!productId||!code||!title||!(discount>0)||min<0||(max!==null&&max<0))return note("Offer details aur valid discount bhariye.",true);
 const r=await sb.rpc("seller_create_product_offer",{p_product_id:productId,p_code:code,p_title:title,p_discount_type:type,p_discount_value:discount,p_min_order_amount:min,p_max_discount:max,p_starts_at:start?new Date(start).toISOString():new Date().toISOString(),p_ends_at:end});
 if(r.error)return note(r.error.message,true);
 ["offerProductId","offerCode","offerTitle","offerDiscount","offerMin","offerMax","offerStart","offerEnd"].forEach(id=>{const x=document.getElementById(id);if(x)x.value=""});
 await loadSellerOffers(); note("Offer Pending admin approval ke liye submit ho gaya.");
}
async function cancelSellerOffer(id){if(!confirm("Offer cancel karein?"))return;const r=await sb.rpc("seller_cancel_product_offer",{p_offer_id:id});if(r.error)return note(r.error.message,true);loadSellerOffers();note("Offer cancel ho gaya.");}
async function loadSellerAnalytics(){
 const e=document.getElementById("sellerAnalytics");if(!e||!seller)return;
 const [p,o,c,ret]=await Promise.all([
  sb.from("products").select("id,stock,status",{count:"exact"}).eq("seller_id",seller.id),
  sb.from("Orders").select("id,order_status,total_amount,payment_status",{count:"exact"}).eq("seller_id",seller.id),
  sb.from("commissions").select("seller_earning,commission_amount,status").eq("seller_id",seller.id),
  sb.from("returns").select("id,status",{count:"exact"}).in("order_id",(await sb.from("Orders").select("id").eq("seller_id",seller.id)).data?.map(x=>x.id)||[])
 ]);
 if(p.error||o.error||c.error){e.textContent=(p.error||o.error||c.error).message;return;}
 const products=p.data||[],orders=o.data||[],comm=c.data||[],low=products.filter(x=>Number(x.stock||0)<=5).length,active=products.filter(x=>x.status==="Active").length;
 const sales=orders.reduce((a,x)=>a+Number(x.total_amount||0),0),earn=comm.reduce((a,x)=>a+Number(x.seller_earning||0),0),commission=comm.reduce((a,x)=>a+Number(x.commission_amount||0),0),returns=(ret.data||[]).length;
 e.innerHTML="<div class='grid'><div><b>Products</b><br>"+(p.count||products.length)+"</div><div><b>Active</b><br>"+active+"</div><div><b>Orders</b><br>"+(o.count||orders.length)+"</div><div><b>Sales value</b><br>₹"+sales.toFixed(2)+"</div><div><b>Seller earning</b><br>₹"+earn.toFixed(2)+"</div><div><b>Commission</b><br>₹"+commission.toFixed(2)+"</div><div><b>Returns</b><br>"+returns+"</div><div><b>Low stock</b><br>"+low+"</div></div>";
}
async function sellerSupportTicket(){
 const subject=document.getElementById("sellerTicketSubject").value.trim(),message=document.getElementById("sellerTicketMessage").value.trim();
 if(subject.length<3||message.length<3)return note("Subject aur message bhariye.",true);
 const r=await sb.rpc("create_support_ticket",{p_order_id:null,p_subject:subject,p_category:"Seller",p_message:message});
 if(r.error)return note(r.error.message,true);
 document.getElementById("sellerTicketSubject").value="";document.getElementById("sellerTicketMessage").value="";loadSellerSupport();note("Support ticket create ho gaya.");
}
async function loadSellerSupport(){
 const e=document.getElementById("sellerSupport");if(!e||!sellerUser)return;
 const r=await sb.from("support_tickets").select("id,subject,status,priority,created_at").eq("user_id",sellerUser.id).eq("category","Seller").order("created_at",{ascending:false}).limit(20);
 if(r.error){e.textContent=r.error.message;return;}
 e.innerHTML=(r.data||[]).map(x=>"<div class='product'><b>"+clean(x.subject)+"</b> | "+clean(x.status)+" | "+clean(x.priority)+"<br>"+new Date(x.created_at).toLocaleString()+"</div>").join("")||"No seller support tickets.";
}
async function loadSellerNotifications(){
 const e=document.getElementById("sellerNotifications");if(!e||!sellerUser)return;
 const r=await sb.from("notifications").select("title,body,type,is_read,created_at").eq("user_id",sellerUser.id).order("created_at",{ascending:false}).limit(20);
 if(r.error){e.textContent=r.error.message;return;}
 e.innerHTML=(r.data||[]).map(x=>"<div class='product'><b>"+clean(x.title||"Notification")+"</b> "+(x.is_read?"":"🔔")+"<br>"+clean(x.body||"")+"<br><small>"+new Date(x.created_at).toLocaleString()+"</small></div>").join("")||"No notifications.";
}
const _oldShowDashboard=showDashboard;
showDashboard=function(){_oldShowDashboard();loadSellerReturns();loadSellerOffers();loadSellerWholesaleInquiries();loadSellerAnalytics();loadSellerSupport();loadSellerNotifications();};

async function loadSellerWholesaleInquiries(){const e=document.getElementById("sellerWholesaleInquiries");if(!e||!seller)return;const r=await sb.from("wholesale_inquiries").select("id,product_id,quantity,target_price,quoted_price,status,note,created_at").eq("seller_id",seller.id).order("created_at",{ascending:false}).limit(50);if(r.error)return e.textContent=r.error.message;e.innerHTML=(r.data||[]).map(x=>"<div class='product'><b>Inquiry "+clean(x.id.slice(0,8))+"…</b><br>Qty: "+x.quantity+" | Target: "+(x.target_price?"₹"+Number(x.target_price).toFixed(2):"—")+" | Status: "+clean(x.status)+"<br>"+clean(x.note||"")+(x.status==="Pending"?'<br><button class="btn alt" onclick="quoteWholesaleInquiry(\''+x.id+'\')">Quote</button><button class="btn alt" onclick="rejectWholesaleInquiry(\''+x.id+'\')">Reject</button>':"")+"</div>").join("")||"No wholesale inquiries.";}
async function quoteWholesaleInquiry(id){const q=Number(prompt("Quote per piece (₹):"));if(!(q>0))return;const r=await sb.rpc("seller_update_wholesale_inquiry",{p_inquiry_id:id,p_status:"Quoted",p_quoted_price:q});if(r.error)return note(r.error.message,true);await loadSellerWholesaleInquiries();note("Wholesale quote sent.");}
async function rejectWholesaleInquiry(id){if(!confirm("Inquiry reject karein?"))return;const r=await sb.rpc("seller_update_wholesale_inquiry",{p_inquiry_id:id,p_status:"Rejected",p_quoted_price:null});if(r.error)return note(r.error.message,true);await loadSellerWholesaleInquiries();note("Wholesale inquiry rejected.");}
