const sb=window.shubhSupabase;
let sellerUser=null,seller=null;
function note(t,bad){const e=document.getElementById("msg");e.className="msg "+(bad?"danger":"ok");e.textContent=t;}
function clean(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
async function sellerLogin(){try{const email=document.getElementById("email").value.trim().toLowerCase(),password=document.getElementById("password").value;if(!email||!password)return note("Email aur password bhariye.",true);if(!window.shubhSupabase)return note("Login service load nahi hui. Page refresh karke dobara try kijiye.",true);const r=await sb.auth.signInWithPassword({email,password});if(r.error){const msg=String(r.error.message||"Login failed");if(/email not confirmed|email_not_confirmed/i.test(msg))return note("Email verify nahi hua hai. Pehle verification email confirm kijiye. 'Resend Verification' se email dobara bhej sakte hain.",true);if(/invalid login credentials/i.test(msg))return note("Email ya password galat hai. 'Forgot Password' se reset kijiye.",true);return note("Login failed: "+msg,true)}if(!r.data?.session)return note("Login session nahi bani. Dobara try kijiye.",true);await bootSeller();}catch(e){note("Login service se connection nahi ho pa raha. Internet check karke page refresh kijiye.",true);console.error(e)}}
async function sellerRegister(){const email=document.getElementById("email").value.trim().toLowerCase(),password=document.getElementById("password").value,sellerType=document.getElementById("sellerType").value,name=document.getElementById("name").value.trim(),mobile=document.getElementById("mobile").value.trim(),shop=document.getElementById("shop").value.trim(),address=document.getElementById("address").value.trim(),pan=document.getElementById("pan").value.trim().toUpperCase(),category=document.getElementById("category").value.trim(),agreement=document.getElementById("sellerAgreement").checked,gstStatus=document.getElementById("gstStatus").value,gstin=document.getElementById("gst").value.trim().toUpperCase(),udyamRegistered=document.getElementById("udyamRegistered").value,udyamNumber=document.getElementById("udyamNumber").value.trim().toUpperCase();if(!email||!password||!name||!mobile||!shop||!address||!pan||!category)return note("Seller type, name, mobile, shop, address, PAN aur category zaroor bhariye.",true);if(!agreement)return note("Seller Agreement aur declaration accept kijiye.",true);if(gstStatus==="registered"&&!gstin)return note("GST Registered select kiya hai, GSTIN dijiye.",true);if(udyamRegistered==="yes"&&!udyamNumber)return note("Udyam Registered select kiya hai, Udyam number dijiye.",true);const draft={sellerType,name,mobile,shop,address,pan,category,agreement,gstStatus,gstin,udyamRegistered,udyamNumber};localStorage.setItem("shubhmart_seller_draft",JSON.stringify(draft));const r=await sb.auth.signUp({email,password,options:{data:{seller_onboarding:draft}}});if(r.error)return note(r.error.message,true);if(r.data.user&&r.data.session)await finishSellerSetup(r.data.user);else note("Registration ho gaya. Email verify karke isi page par Login kijiye.");}
async function resendSellerVerification(){const email=document.getElementById("email").value.trim().toLowerCase();if(!email)return note("Pehle email bhariye.",true);const r=await sb.auth.resend({type:"signup",email});if(r.error)return note("Verification email nahi bheji gayi: "+r.error.message,true);note("Verification email dobara bhej di gayi. Inbox/Spam check kijiye.");}
async function sellerForgotPassword(){const email=document.getElementById("email").value.trim().toLowerCase();if(!email)return note("Password reset ke liye email bhariye.",true);const redirectTo=window.location.origin+window.location.pathname;const r=await sb.auth.resetPasswordForEmail(email,{redirectTo});if(r.error)return note("Password reset email nahi bheji gayi: "+r.error.message,true);note("Password reset email bhej di gayi. Inbox/Spam check kijiye.");}

async function finishSellerSetup(user){const local=JSON.parse(localStorage.getItem("shubhmart_seller_draft")||"{}");const d=Object.keys(local).length?local:(user.user_metadata?.seller_onboarding||{});if(!d.name||!d.mobile||!d.shop||!d.address||!d.pan||!d.category)return note("Seller onboarding details missing. Registration form dobara complete kijiye.",true);let r=await sb.from("profiles").upsert({id:user.id,full_name:d.name,phone:d.mobile,role:"seller"},{onConflict:"id"});if(r.error)return note("Seller profile error: "+r.error.message,true);r=await sb.from("Sellers").upsert({user_id:user.id,seller_name:d.name,mobile:d.mobile,email:user.email||"",shop_name:d.shop,address:d.address,pan:d.pan,gst_number:d.gstin||null,gst_status:d.gstStatus||"not_provided",udyam_registered:d.udyamRegistered==="yes",udyam_number:d.udyamNumber||null,status:"Pending",kyc_status:"Pending",entity_type:d.sellerType||"individual"},{onConflict:"user_id"}).select().single();if(r.error)return note("Seller setup error: "+r.error.message,true);seller=r.data;sellerUser=user;const app={seller_id:user.id,seller_type:d.sellerType||"individual",seller_name:d.name,mobile:d.mobile,email:user.email||"",address:d.address,pan:d.pan,gstin:d.gstin||null,category:d.category,entity_type:d.sellerType||"individual",gst_status:d.gstStatus||"not_provided",udyam_registered:d.udyamRegistered==="yes",udyam_number:d.udyamNumber||null,wholesale_enabled:false,declaration_accepted:!!d.agreement,agreement_accepted:!!d.agreement,agreement_version:"1.0",seller_agreement_accepted_at:new Date().toISOString()};r=await sb.from("seller_applications").upsert(app,{onConflict:"seller_id"});if(r.error)return note("Seller application error: "+r.error.message,true);localStorage.removeItem("shubhmart_seller_draft");showDashboard();}
async function bootSeller(){try{const r=await sb.auth.getUser();if(r.error)return note("Session check failed: "+r.error.message,true);const user=r.data.user;if(!user)return;sellerUser=user;let q=await sb.from("Sellers").select("*").eq("user_id",user.id).maybeSingle();if(q.error)return note("Seller profile load error: "+q.error.message,true);if(!q.data){let d={};try{d=JSON.parse(localStorage.getItem("shubhmart_seller_draft")||"{}")}catch(e){localStorage.removeItem("shubhmart_seller_draft")}if(d.name)return finishSellerSetup(user);const meta=user.user_metadata?.seller_onboarding;if(meta?.name)return finishSellerSetup(user);return note("Seller profile nahi mila. New Seller Registration kijiye.",true);}seller=q.data;showDashboard();}catch(e){note("Seller dashboard load nahi ho pa raha. Page refresh karke dobara try kijiye.",true);console.error(e)}}
function showDashboard(){document.getElementById("authPanel").classList.add("hidden");document.getElementById("dashboard").classList.remove("hidden");document.getElementById("logoutBtn").classList.remove("hidden");document.getElementById("sellerTitle").textContent=(seller.shop_name||seller.seller_name||"Seller")+" — Dashboard";document.getElementById("sellerStatus").textContent="Account: "+(seller.status||"Pending")+" | KYC: "+(seller.kyc_status||"Pending");document.getElementById("pSellerName").value=seller.seller_name||"";document.getElementById("pMobile").value=seller.mobile||"";document.getElementById("pShop").value=seller.shop_name||"";document.getElementById("pAddress").value=seller.address||"";document.getElementById("pPan").value=seller.pan||"";document.getElementById("pGst").value=seller.gst_number||"";loadMyProducts();loadMyOrders();loadKyc();loadSellerFinance();}
async function saveSellerProfile(){const patch={p_seller_id:seller.id,p_seller_name:document.getElementById("pSellerName").value.trim(),p_mobile:document.getElementById("pMobile").value.trim(),p_shop_name:document.getElementById("pShop").value.trim(),p_address:document.getElementById("pAddress").value.trim(),p_pan:document.getElementById("pPan").value.trim(),p_gst:document.getElementById("pGst").value.trim()};const r=await sb.rpc("update_seller_profile",patch);if(r.error)return note(r.error.message,true);seller={...seller,seller_name:patch.p_seller_name,mobile:patch.p_mobile,shop_name:patch.p_shop_name,address:patch.p_address,pan:patch.p_pan,gst_number:patch.p_gst};document.getElementById("sellerTitle").textContent=(seller.shop_name||seller.seller_name)+" — Dashboard";note("Shop profile securely saved.");}
async function addSellerProduct(){const name=document.getElementById("prodName").value.trim(),category=document.getElementById("prodCategory").value.trim(),price=Number(document.getElementById("prodPrice").value),mrp=Number(document.getElementById("prodMrp").value),stock=Math.max(0,Number(document.getElementById("prodStock").value||0)),image_url=document.getElementById("prodImage").value.trim(),description=document.getElementById("prodDescription").value.trim();if(!seller||!name||!category||!(price>0))return note("Seller profile, product name, category aur valid price bhariye.",true);const r=await sb.from("products").insert({name,category,price,mrp:mrp>0?mrp:null,stock,image_url,description,seller_id:seller.id,status:"Pending"}).select("id").single();if(r.error)return note("Product add error: "+r.error.message,true);const bulkMin=Math.floor(Number(document.getElementById("bulkMin").value||0)),bulkMax=Math.floor(Number(document.getElementById("bulkMax").value||0)),bulkPrice=Number(document.getElementById("bulkPrice").value||0);if(bulkMin>1&&bulkPrice>0){if(bulkMax&&bulkMax<bulkMin)return note("Bulk max quantity, min quantity se kam nahi ho sakti.",true);const wr=await sb.from("wholesale_pricing").insert({product_id:r.data.id,seller_id:seller.id,min_quantity:bulkMin,max_quantity:bulkMax||null,unit_price:bulkPrice,status:"Pending"});if(wr.error)return note("Bulk pricing error: "+wr.error.message,true);}["prodName","prodCategory","prodPrice","prodMrp","prodStock","prodImage","prodDescription","bulkMin","bulkMax","bulkPrice"].forEach(id=>document.getElementById(id).value="");await loadMyProducts();note("Product submit ho gaya. Status: Pending.");}
async function addSellerVariant(){if(!seller)return;const productId=document.getElementById("variantProductId").value.trim(),sku=document.getElementById("variantSku").value.trim(),variantName=document.getElementById("variantName").value.trim(),optionValue=document.getElementById("variantValue").value.trim(),price=Number(document.getElementById("variantPrice").value),mrp=Number(document.getElementById("variantMrp").value),stock=Math.floor(Number(document.getElementById("variantStock").value||0)),image_url=document.getElementById("variantImage").value.trim();if(!productId||!variantName||!optionValue||!(price>0)||!(mrp>=price)||stock<0)return note("Variant details aur valid price/MRP/stock bhariye.",true);const r=await sb.rpc("seller_add_product_variant",{p_product_id:productId,p_sku:sku||null,p_variant_name:variantName,p_option_value:optionValue,p_price:price,p_mrp:mrp,p_stock:stock,p_image_url:image_url||null});if(r.error)return note("Variant add error: "+r.error.message,true);note("Variant Pending approval ke liye save ho gaya.");loadSellerVariants(productId);}
async function loadSellerVariants(productId){const e=document.getElementById("sellerVariants");if(!productId)return;e.textContent="Loading…";const r=await sb.from("product_variants").select("id,sku,variant_name,option_value,price,mrp,stock,status").eq("product_id",productId).order("created_at",{ascending:false});if(r.error)return e.textContent=r.error.message;e.innerHTML=(r.data||[]).map(v=>"<div class='product'><b>"+clean(v.variant_name)+"</b>: "+clean(v.option_value)+" | SKU "+clean(v.sku||"-")+" | ₹"+Number(v.price||0).toFixed(2)+" | Stock "+Number(v.stock||0)+" | "+clean(v.status)+"</div>").join("")||"No variants yet.";}
async function updateBulkStock(){const id=document.getElementById("bulkStockProductId").value.trim(),v=Math.floor(Number(document.getElementById("bulkStockValue").value));if(!id||!Number.isInteger(v)||v<0)return note("Product ID aur valid stock bhariye.",true);const r=await sb.rpc("update_seller_product_stock",{p_product_id:id,p_stock:v});if(r.error)return note(r.error.message,true);document.getElementById("bulkStockMsg").textContent="Stock updated securely.";loadMyProducts();}
async function loadMyProducts(){const r=await sb.from("products").select("id,name,category,price,mrp,stock,image_url,status,created_at").eq("seller_id",seller.id).order("created_at",{ascending:false});const e=document.getElementById("myProducts");if(r.error)return e.textContent=r.error.message;const products=r.data||[];const dl=document.getElementById("sellerProductOptions");if(dl)dl.innerHTML=products.map(p=>`<option value="${clean(p.id)}">${clean(p.name)} — ${clean(p.category||"")}</option>`).join("");e.innerHTML=products.length?products.map(p=>`<div class="product"><b>${clean(p.name)}</b><div>SKU/Product ID: <span class="small">${clean(p.id)}</span></div><div>₹${Number(p.price||0).toFixed(2)} | Stock: ${Number(p.stock||0)} | ${clean(p.status)}</div><div class="row"><input id="stock_${p.id}" type="number" min="0" value="${Number(p.stock||0)}"><button class="btn alt" onclick="updateSellerStock('${p.id}')">Save Stock</button><button class="btn alt" onclick="editSellerProduct('${p.id}')">Edit Product</button></div></div>`).join(""):"No products yet.";}
async function editSellerProduct(id){
 const q=await sb.from("products").select("id,name,category,price,mrp,stock,description,status").eq("id",id).eq("seller_id",seller.id).maybeSingle();
 if(q.error||!q.data)return note(q.error?.message||"Product nahi mila.",true);
 if(!["Pending","Under Review","Rejected"].includes(q.data.status))return note("Approved/Live product ko is screen se edit nahi kiya ja sakta. Pehle admin workflow ke through update request karein.",true);
 document.getElementById("editProductId").value=q.data.id;
 document.getElementById("editName").value=q.data.name||"";
 document.getElementById("editCategory").value=q.data.category||"";
 document.getElementById("editPrice").value=q.data.price??"";
 document.getElementById("editMrp").value=q.data.mrp??"";
 document.getElementById("editStock").value=q.data.stock??0;
 document.getElementById("editDescription").value=q.data.description||"";
 document.getElementById("editProductMsg").className="msg hidden";
 document.getElementById("sellerEditModal").classList.remove("hidden");
 document.getElementById("editName").focus();
}
function closeSellerEdit(){document.getElementById("sellerEditModal")?.classList.add("hidden");}
async function saveSellerProductEdit(){
 const id=document.getElementById("editProductId").value,name=document.getElementById("editName").value.trim(),category=document.getElementById("editCategory").value.trim(),price=Number(document.getElementById("editPrice").value),mrp=Number(document.getElementById("editMrp").value||0),stock=Math.floor(Number(document.getElementById("editStock").value)),description=document.getElementById("editDescription").value.trim(),m=document.getElementById("editProductMsg");
 if(!id||!name||!category||!(price>0)||stock<0||!Number.isInteger(stock)||(mrp>0&&mrp<price)){m.className="msg danger";m.textContent="Product name, category, valid price, MRP aur stock check kijiye.";return;}
 const r=await sb.from("products").update({name,category,price,mrp:mrp>0?mrp:null,stock,description,status:"Pending",is_live:false,compliance_status:"Pending"}).eq("id",id).eq("seller_id",seller.id);
 if(r.error){m.className="msg danger";m.textContent="Product update error: "+r.error.message;return;}
 closeSellerEdit();await loadMyProducts();note("Product update ho gaya aur dobara admin approval ke liye Pending hai.");
}
async function updateSellerStock(id){const v=Math.floor(Number(document.getElementById("stock_"+id)?.value));if(!Number.isInteger(v)||v<0)return note("Valid stock bhariye.",true);const r=await sb.rpc("update_seller_product_stock",{p_product_id:id,p_stock:v});if(r.error)return note(r.error.message,true);await loadMyProducts();note("Stock securely updated.");}
async function submitSellerKyc(){if(!seller)return;const t=document.getElementById("kycType").value.trim(),n=document.getElementById("kycNumber").value.trim(),u=document.getElementById("kycUrl").value.trim();const r=await sb.rpc("submit_seller_kyc",{p_seller_id:seller.id,p_document_type:t,p_document_number:n,p_document_url:u||null});if(r.error)return note(r.error.message,true);document.getElementById("kycStatus").textContent="KYC status: Pending admin review";seller.kyc_status="Pending";document.getElementById("sellerStatus").textContent="Account: "+(seller.status||"Pending")+" | KYC: Pending";note("KYC securely submitted for admin review.");}
async function loadKyc(){const r=await sb.from("seller_kyc").select("document_type,status,rejection_reason,created_at").eq("seller_id",seller.id).order("created_at",{ascending:false}).limit(1).maybeSingle();const e=document.getElementById("kycStatus");if(r.error)return e.textContent=r.error.message;if(!r.data)return e.textContent="KYC: Not submitted";e.textContent="KYC: "+r.data.status+" | "+clean(r.data.document_type)+(r.data.rejection_reason?" | "+clean(r.data.rejection_reason):"");}
async function loadMyOrders(){const r=await sb.from("Orders").select("id,total_amount,order_status,payment_status,created_at").eq("seller_id",seller.id).order("created_at",{ascending:false}).limit(30);const e=document.getElementById("myOrders");if(r.error)return e.textContent=r.error.message;if(!r.data?.length)return e.textContent="No seller orders yet.";const ids=r.data.map(o=>o.id);const sh=ids.length?await sb.from("shipments").select("order_id,tracking_number,shipment_status,estimated_delivery_at").in("order_id",ids):{data:[]};const map=Object.fromEntries((sh.data||[]).map(x=>[x.order_id,x]));e.innerHTML=r.data.map(o=>{const s=map[o.id];const next={Pending:["Confirmed","Cancelled"],Confirmed:["Processing","Cancelled"],Processing:["Packed","Cancelled"],Packed:["Dispatched"]};const actions=(next[o.order_status]||[]).map(st=>`<button class="btn alt" onclick="updateSellerOrderStatus('${o.id}','${st}')">${st}</button>`).join("");return `<div class="panel"><b>Order ${clean(o.id.slice(0,8))}…</b><br>₹${Number(o.total_amount||0).toFixed(2)} | ${clean(o.order_status)} | Payment: ${clean(o.payment_status)}<br>🚚 ${clean(s?.shipment_status||"Shipment pending")}${s?.tracking_number?" | "+clean(s.tracking_number):""}<div>${actions}</div></div>`}).join("");}
async function updateSellerOrderStatus(id,status){if(!confirm("Order status '"+status+"' set karein?"))return;const r=await sb.rpc("update_seller_order_status",{p_order_id:id,p_status:status});if(r.error)return note(r.error.message,true);await loadMyOrders();note("Order status updated securely.");}
async function requestSellerPayout(){const amount=Number(prompt("Kitna payout request karna hai?"));if(!(amount>0))return note("Valid payout amount bhariye.",true);const r=await sb.rpc("request_seller_payout",{p_amount:amount});if(r.error)return note(r.error.message,true);await loadSellerFinance();note("Payout request Pending mein save ho gayi.");}\nasync function loadSellerFinance(){const e=document.getElementById("sellerFinance");const [c,p]=await Promise.all([sb.from("commissions").select("gross_amount,commission_amount,seller_earning,status,created_at").eq("seller_id",seller.id).order("created_at",{ascending:false}).limit(50),sb.from("payouts").select("amount,status,payout_reference,requested_at,paid_at").eq("seller_id",seller.id).order("requested_at",{ascending:false}).limit(20)]);if(c.error||p.error)return e.textContent=(c.error||p.error).message;const earn=(c.data||[]).reduce((a,x)=>a+Number(x.seller_earning||0),0),comm=(c.data||[]).reduce((a,x)=>a+Number(x.commission_amount||0),0);e.innerHTML=`<b>Seller earnings:</b> ₹${earn.toFixed(2)}<br><b>Commission:</b> ₹${comm.toFixed(2)}<br><b>Commission records:</b> ${(c.data||[]).length}<br><button class="btn" onclick="requestSellerPayout()">Request Payout</button><hr><b>Recent payouts:</b><br>${((p.data||[]).map(x=>"₹"+Number(x.amount||0).toFixed(2)+" — "+clean(x.status)+" — "+clean(x.payout_reference||"")).join("<br>")||"No payouts yet.")}`;}
async function sellerLogout(){await sb.auth.signOut();location.reload();}
sb.auth.onAuthStateChange((event,session)=>{if(session&&!sellerUser)setTimeout(bootSeller,0);});
bootSeller();
async function generateAIListing(){const input=document.getElementById("aiListingInput")?.value.trim();if(!input)return note("Product details likhiye.",true);const box=document.getElementById("aiListingResult");box.textContent="AI draft bana raha hai…";try{const r=await shubhAI("listing",{input});box.innerHTML='<div class="panel"><b>Title</b><input id="aiTitle" value="'+clean(r.title)+'"><b>Description</b><textarea id="aiDesc">'+clean(r.description)+'</textarea><b>Category</b><input id="aiCategory" value="'+clean(r.category)+'"><div>Quality score: <b>'+Number(r.quality_score||0)+'/100</b></div><div class="small">Keywords: '+clean((r.keywords||[]).join(", "))+'</div><button class="btn" onclick="useAIListing()">Use in Product Form</button><button class="btn alt" onclick="saveAIDraft()">Save Draft</button></div>';window._aiListing=r;}catch(e){box.textContent="AI service error: "+e.message;}}
function useAIListing(){const r=window._aiListing||{};document.getElementById("prodName").value=r.title||"";document.getElementById("prodCategory").value=r.category||"";document.getElementById("prodDescription").value=r.description||"";note("AI draft product form mein aa gaya. Price/stock check karke submit kijiye.");}
async function saveAIDraft(){if(!seller||!window._aiListing)return;const x=await sb.from("ai_listing_drafts").insert({seller_id:seller.id,input_text:document.getElementById("aiListingInput").value.trim(),output:window._aiListing,status:"Draft"});if(x.error)return note("AI draft save error: "+x.error.message,true);note("AI draft secure seller history mein save ho gaya.");}

async function loadSellerReturns(){
 const e=document.getElementById("sellerReturns"); if(!e||!seller)return;
 const orders=await sb.from("Orders").select("id").eq("seller_id",seller.id).limit(200);
 if(orders.error){e.textContent=orders.error.message;return;}
 const ids=(orders.data||[]).map(x=>x.id); if(!ids.length){e.textContent="No return/RTO requests yet.";return;}
 const r=await sb.from("returns").select("id,order_id,status,return_type,reason_code,refund_amount,refund_status,pickup_status,requested_at,decision_at").in("order_id",ids).order("requested_at",{ascending:false}).limit(50);
 if(r.error){e.textContent=r.error.message;return;}
 e.innerHTML=(r.data||[]).map(x=>"<div class='product'><b>Return "+clean(x.id.slice(0,8))+"…</b><br>Order: "+clean(x.order_id.slice(0,8))+"… | "+clean(x.return_type)+" | "+clean(x.status)+"<br>Reason: "+clean(x.reason_code||"-")+" | Refund: ₹"+Number(x.refund_amount||0).toFixed(2)+" ("+clean(x.refund_status||"-")+")<br>Pickup: "+clean(x.pickup_status||"-")+"</div>").join("")||"No return/RTO requests yet.";
}
async function loadSellerOffers(){
 const e=document.getElementById("sellerOffers"); if(!e||!seller)return;
 const r=await sb.from("product_offers").select("id,product_id,code,title,discount_type,discount_value,min_order_amount,max_discount,starts_at,ends_at,status").eq("seller_id",seller.id).order("created_at",{ascending:false}).limit(50);
 if(r.error){e.textContent=r.error.message;return;}
 e.innerHTML=(r.data||[]).map(x=>"<div class='product'><b>"+clean(x.title)+"</b> — "+clean(x.code)+"<br>Product: "+clean(x.product_id)+" | "+clean(x.discount_type)+" "+Number(x.discount_value||0)+" | Min ₹"+Number(x.min_order_amount||0).toFixed(2)+" | "+clean(x.status)+"<br><button class='btn alt' onclick=\"cancelSellerOffer('"+x.id+"')\">Cancel Offer</button></div>").join("")||"No offers yet.";
}
async function addSellerOffer(){
 const productId=document.getElementById("offerProductId").value.trim(),code=document.getElementById("offerCode").value.trim(),title=document.getElementById("offerTitle").value.trim(),type=document.getElementById("offerType").value,discount=Number(document.getElementById("offerDiscount").value),min=Number(document.getElementById("offerMin").value||0),maxRaw=document.getElementById("offerMax").value, max=maxRaw===""?null:Number(maxRaw),start=document.getElementById("offerStart").value,endRaw=document.getElementById("offerEnd").value,end=endRaw?new Date(endRaw).toISOString():null;
 if(!productId||!code||!title||!(discount>0)||min<0||(max!==null&&max<0))return note("Offer details aur valid discount bhariye.",true);
 const r=await sb.rpc("seller_create_product_offer",{p_product_id:productId,p_code:code,p_title:title,p_discount_type:type,p_discount_value:discount,p_min_order_amount:min,p_max_discount:max,p_starts_at:start?new Date(start).toISOString():new Date().toISOString(),p_ends_at:end});
 if(r.error)return note(r.error.message,true);
 ["offerProductId","offerCode","offerTitle","offerDiscount","offerMin","offerMax","offerStart","offerEnd"].forEach(id=>{const x=document.getElementById(id);if(x)x.value=""});
 await loadSellerOffers(); note("Offer Pending admin approval ke liye submit ho gaya.");
}
async function cancelSellerOffer(id){if(!confirm("Offer cancel karein?"))return;const r=await sb.rpc("seller_cancel_product_offer",{p_offer_id:id});if(r.error)return note(r.error.message,true);loadSellerOffers();note("Offer cancel ho gaya.");}
async function loadSellerAnalytics(){
 const e=document.getElementById("sellerAnalytics");if(!e||!seller)return;
 const [p,o,c,ret]=await Promise.all([
  sb.from("products").select("id,stock,status",{count:"exact"}).eq("seller_id",seller.id),
  sb.from("Orders").select("id,order_status,total_amount,payment_status",{count:"exact"}).eq("seller_id",seller.id),
  sb.from("commissions").select("seller_earning,commission_amount,status").eq("seller_id",seller.id),
  sb.from("returns").select("id,status",{count:"exact"}).in("order_id",(await sb.from("Orders").select("id").eq("seller_id",seller.id)).data?.map(x=>x.id)||[])
 ]);
 if(p.error||o.error||c.error){e.textContent=(p.error||o.error||c.error).message;return;}
 const products=p.data||[],orders=o.data||[],comm=c.data||[],low=products.filter(x=>Number(x.stock||0)<=5).length,active=products.filter(x=>x.status==="Active").length;
 const sales=orders.reduce((a,x)=>a+Number(x.total_amount||0),0),earn=comm.reduce((a,x)=>a+Number(x.seller_earning||0),0),commission=comm.reduce((a,x)=>a+Number(x.commission_amount||0),0),returns=(ret.data||[]).length,cancelled=orders.filter(x=>String(x.order_status||"").toLowerCase()==="cancelled").length,pendingFulfil=orders.filter(x=>["Pending","Confirmed","Processing","Packed"].includes(x.order_status)).length,openOver48=orders.filter(x=>["Pending","Confirmed"].includes(x.order_status)&&Date.now()-new Date(x.created_at).getTime()>48*60*60*1000).length,cancelRate=orders.length?(cancelled/orders.length*100).toFixed(1):"0.0",returnRate=orders.length?(returns/orders.length*100).toFixed(1):"0.0";
 e.innerHTML="<div class='grid'><div><b>Products</b><br>"+(p.count||products.length)+"</div><div><b>Active</b><br>"+active+"</div><div><b>Orders</b><br>"+(o.count||orders.length)+"</div><div><b>Sales value</b><br>₹"+sales.toFixed(2)+"</div><div><b>Seller earning</b><br>₹"+earn.toFixed(2)+"</div><div><b>Commission</b><br>₹"+commission.toFixed(2)+"</div><div><b>Returns</b><br>"+returns+" ("+returnRate+"%)</div><div><b>Cancellation</b><br>"+cancelled+" ("+cancelRate+"%)</div><div><b>Pending fulfilment</b><br>"+pendingFulfil+"</div><div><b>Low stock</b><br>"+low+"</div><div><b>Orders >48h pending</b><br>"+openOver48+"</div></div><div class='msg' style='margin-top:10px'><b>Account Health:</b> "+(openOver48>0?"Pending orders ko jaldi process kijiye.":"Current visible order metrics normal tracking mein hain.")+" Returns/cancellations ko regularly review kijiye.</div>";
}
async function sellerSupportTicket(){
 const subject=document.getElementById("sellerTicketSubject").value.trim(),message=document.getElementById("sellerTicketMessage").value.trim();
 if(subject.length<3||message.length<3)return note("Subject aur message bhariye.",true);
 const r=await sb.rpc("create_support_ticket",{p_order_id:null,p_subject:subject,p_category:"Seller",p_message:message});
 if(r.error)return note(r.error.message,true);
 document.getElementById("sellerTicketSubject").value="";document.getElementById("sellerTicketMessage").value="";loadSellerSupport();note("Support ticket create ho gaya.");
}
async function loadSellerSupport(){
 const e=document.getElementById("sellerSupport");if(!e||!sellerUser)return;
 const r=await sb.from("support_tickets").select("id,subject,status,priority,created_at").eq("user_id",sellerUser.id).eq("category","Seller").order("created_at",{ascending:false}).limit(20);
 if(r.error){e.textContent=r.error.message;return;}
 e.innerHTML=(r.data||[]).map(x=>"<div class='product'><b>"+clean(x.subject)+"</b> | "+clean(x.status)+" | "+clean(x.priority)+"<br>"+new Date(x.created_at).toLocaleString()+"</div>").join("")||"No seller support tickets.";
}
async function loadSellerNotifications(){
 const e=document.getElementById("sellerNotifications");if(!e||!sellerUser)return;
 const r=await sb.from("notifications").select("title,body,type,is_read,created_at").eq("user_id",sellerUser.id).order("created_at",{ascending:false}).limit(20);
 if(r.error){e.textContent=r.error.message;return;}
 e.innerHTML=(r.data||[]).map(x=>"<div class='product'><b>"+clean(x.title||"Notification")+"</b> "+(x.is_read?"":"🔔")+"<br>"+clean(x.body||"")+"<br><small>"+new Date(x.created_at).toLocaleString()+"</small></div>").join("")||"No notifications.";
}
const _oldShowDashboard=showDashboard;
showDashboard=function(){_oldShowDashboard();loadSellerReturns();loadSellerOffers();loadSellerWholesaleInquiries();loadSellerWholesaleMarket();loadSellerAnalytics();loadSellerSupport();loadSellerNotifications();};

async function loadSellerWholesaleMarket(){
 const e=document.getElementById('sellerWholesaleMarket'); if(!e||!seller)return;
 e.textContent='Wholesale products loading...';
 const r=await sb.from('products').select('id,name,category,price,stock,image_url,wholesale_moq,wholesale_price,seller_id').eq('status','Active').eq('is_live',true).eq('wholesale_enabled',true).not('wholesale_price','is',null).neq('seller_id',seller.id).gt('stock',0).order('created_at',{ascending:false}).limit(30);
 if(r.error){e.textContent=r.error.message;return}
 e.innerHTML=(r.data||[]).length?(r.data||[]).map(p=>'<div class="product"><img src="'+clean(p.image_url||'https://placehold.co/500x300?text=Wholesale')+'" alt="'+clean(p.name)+'"><b>'+clean(p.name)+'</b><div>'+clean(p.category||'')+' · Retail ₹'+Number(p.price||0).toFixed(0)+'</div><div style="color:#075985;font-weight:900">Wholesale ₹'+Number(p.wholesale_price||0).toFixed(0)+' / piece</div><div>MOQ: '+Number(p.wholesale_moq||1)+' · Stock: '+Number(p.stock||0)+'</div><div class="small">🔒 Direct seller contact hidden</div><button class="btn" onclick="sendSellerWholesaleInquiry(\''+p.id+'\')">Send Wholesale Inquiry</button></div>').join(''):'No approved wholesale products available.';
}
async function sendSellerWholesaleInquiry(productId){
 if(!sellerUser)return note('Pehle Seller Panel mein login kijiye.',true);
 const qty=Math.floor(Number(prompt('Wholesale quantity / MOQ se kam nahi:')||0)); if(!qty)return;
 const targetRaw=prompt('Target price per piece (optional):'); const target=targetRaw?Number(targetRaw):null;
 if(targetRaw && !(target>0))return note('Valid target price dijiye.',true);
 const noteText=(prompt('Requirement note (optional):')||'').slice(0,500);
 const r=await sb.rpc('create_wholesale_inquiry',{p_product_id:productId,p_quantity:qty,p_target_price:target,p_note:noteText});
 if(r.error)return note('Wholesale inquiry send nahi hui: '+r.error.message,true);
 note('Wholesale inquiry ShubhMart ke through bhej di gayi ✅'); await loadSellerWholesaleMarket();
}
async function loadSellerWholesaleInquiries(){const e=document.getElementById("sellerWholesaleInquiries");if(!e||!seller)return;const r=await sb.from("wholesale_inquiries").select("id,product_id,quantity,target_price,quoted_price,status,note,created_at").eq("seller_id",seller.id).order("created_at",{ascending:false}).limit(50);if(r.error)return e.textContent=r.error.message;e.innerHTML=(r.data||[]).map(x=>"<div class='product'><b>Inquiry "+clean(x.id.slice(0,8))+"…</b><br>Qty: "+x.quantity+" | Target: "+(x.target_price?"₹"+Number(x.target_price).toFixed(2):"—")+" | Status: "+clean(x.status)+"<br>"+clean(x.note||"")+(x.status==="Pending"?'<br><button class="btn alt" onclick="quoteWholesaleInquiry(\''+x.id+'\')">Quote</button><button class="btn alt" onclick="rejectWholesaleInquiry(\''+x.id+'\')">Reject</button>':"")+"</div>").join("")||"No wholesale inquiries.";}
async function quoteWholesaleInquiry(id){const q=Number(prompt("Quote per piece (₹):"));if(!(q>0))return;const r=await sb.rpc("seller_update_wholesale_inquiry",{p_inquiry_id:id,p_status:"Quoted",p_quoted_price:q});if(r.error)return note(r.error.message,true);await loadSellerWholesaleInquiries();note("Wholesale quote sent.");}
async function rejectWholesaleInquiry(id){if(!confirm("Inquiry reject karein?"))return;const r=await sb.rpc("seller_update_wholesale_inquiry",{p_inquiry_id:id,p_status:"Rejected",p_quoted_price:null});if(r.error)return note(r.error.message,true);await loadSellerWholesaleInquiries();note("Wholesale inquiry rejected.");}
