const sb=window.shubhSupabase;let user=null,products=[];
function note(t,bad){const e=document.getElementById("msg");e.className="msg "+(bad?"danger":"ok");e.textContent=t}
function clean(v){return String(v??"").replace(/[&<>"]/g,"")}
async function boot(){const r=await sb.auth.getUser();user=r.data.user||null;await loadWholesaleProducts();await loadInquiries();await loadBuyerAddresses();await loadWholesaleOrders();await loadPurchaseOrders()}
async function loadWholesaleProducts(){const term=document.getElementById("search").value.trim().toLowerCase();let q=sb.from("products").select("id,name,category,price,mrp,stock,image_url,description,seller_id").eq("status","Active").order("created_at",{ascending:false}).limit(60);const r=await q;if(r.error){document.getElementById("products").textContent=r.error.message;return}products=r.data||[];const ids=products.map(p=>p.id);let pricing=[];if(ids.length){const pr=await sb.from("wholesale_pricing").select("product_id,min_quantity,max_quantity,unit_price").eq("status","Active").in("product_id",ids).order("min_quantity",{ascending:true});pricing=pr.data||[]}const by={};pricing.forEach(x=>(by[x.product_id]??=[]).push(x));const filtered=products.filter(p=>!term||[p.name,p.category,p.description].join(" ").toLowerCase().includes(term));document.getElementById("products").innerHTML=filtered.length?filtered.map(p=>{const tiers=by[p.id]||[];return "<div class='card'>"+(p.image_url?"<img src='"+clean(p.image_url)+"' alt=''>":"")+"<h3>"+clean(p.name)+"</h3><div>"+clean(p.category||"")+"</div><p>Retail: ₹"+Number(p.price||0).toFixed(2)+"</p>"+(tiers.length?"<b>Bulk rates</b><div class='small'>"+tiers.map(t=>t.min_quantity+"+ pcs → ₹"+Number(t.unit_price).toFixed(2)+"/pc").join("<br>")+"</div>":"<div class='small'>Bulk quote available</div>")+"<button class='btn' onclick='openInquiry(\""+p.id+"\")'>Bulk Inquiry</button></div>"}).join(""):"No active wholesale products yet."}
async function openInquiry(id){if(!user){note("Bulk inquiry ke liye pehle Customer Store par login kijiye.",true);return}const p=products.find(x=>x.id===id);if(!p)return;const qty=Math.floor(Number(prompt("Kitni quantity chahiye?", "10")));if(!(qty>1))return note("Quantity 2 ya usse zyada honi chahiye.",true);const target=prompt("Aapka target price per piece? (optional)","");const noteText=prompt("Requirement / delivery note? (optional)","")||"";const r=await sb.from("wholesale_inquiries").insert({buyer_id:user.id,product_id:p.id,seller_id:p.seller_id,quantity:qty,target_price:target&&Number(target)>0?Number(target):null,note:noteText});if(r.error)return note("Inquiry error: "+r.error.message,true);note("Bulk inquiry seller ko bhej di gayi. Quotation aane par status yahan dikhega.");await loadInquiries()}
async function loadInquiries(){const e=document.getElementById("inquiries");if(!user){e.textContent="Login karke apni inquiries dekhein.";return}const r=await sb.from("wholesale_inquiries").select("id,product_id,quantity,target_price,quoted_price,status,note,created_at").eq("buyer_id",user.id).order("created_at",{ascending:false}).limit(30);if(r.error){e.textContent=r.error.message;return}const names={};(products||[]).forEach(p=>names[p.id]=p.name);e.innerHTML=r.data?.length?r.data.map(x=>{const action=x.status==="Quoted"?"<br><button class='btn' onclick='acceptWholesaleInquiry(\'"+x.id+"\')'>Accept Quote</button><button class='btn alt' onclick='cancelWholesaleInquiry(\'"+x.id+"\')'>Cancel</button>":"";return "<div class='card'><b>"+clean(names[x.product_id]||"Product")+"</b><br>Qty: "+x.quantity+" | Status: "+clean(x.status)+"<br>"+(x.quoted_price?"Seller quote: ₹"+Number(x.quoted_price).toFixed(2)+"/pc":"Waiting for seller quote")+action+(x.status==="Accepted"?"<br><button class=\"btn\" onclick=\"createWholesaleOrder(\'"+x.id+"\')\">Create Bulk Order</button>":"")+ "</div>"}).join(""):"No bulk inquiries yet."}
sb.auth.onAuthStateChange((event,session)=>{user=session?.user||null;setTimeout(loadInquiries,0)});boot();

async function saveBuyerBusinessProfile(){if(!user)return note("Pehle login kijiye.",true);const name=document.getElementById("buyerBusinessName").value.trim(),gst=document.getElementById("buyerGst").value.trim();if(!name)return note("Business name bhariye.",true);const r=await sb.rpc("save_wholesale_buyer_profile",{p_business_name:name,p_gstin:gst||null});if(r.error)return note(r.error.message,true);note("Business profile saved.");}
async function loadWholesaleOrders(){const e=document.getElementById("wholesaleOrders");if(!e||!user)return;if(!document.getElementById("wholesaleAddress"))await loadBuyerAddresses();const r=await sb.from("wholesale_orders").select("id,order_id,product_id,quantity,unit_price,total_amount,status,created_at").eq("buyer_id",user.id).order("created_at",{ascending:false}).limit(30);if(r.error){e.textContent=r.error.message;return}e.innerHTML=r.data?.length?r.data.map(x=>"<div class='card'><b>Order "+clean(x.order_id||x.id)+"</b><br>Qty: "+x.quantity+" × ₹"+Number(x.unit_price).toFixed(2)+" = ₹"+Number(x.total_amount).toFixed(2)+"<br>Status: "+clean(x.status)+"<br><button class='btn' onclick='makeWholesalePO(\""+x.id+"\")'>Create PO</button> <button class='btn' onclick='repeatWholesaleOrder(\""+x.id+"\")'>Repeat Order</button><button class='btn alt' onclick='printWholesaleInvoice(\""+x.id+"\")'>Invoice</button></div>").join(""):"No wholesale orders yet."}
async function makeWholesalePO(id){const po=prompt("PO Number (example: PO-2026-001)");if(!po)return;const notes=prompt("PO notes (optional)","")||"";const r=await sb.rpc("create_wholesale_purchase_order",{p_wholesale_order_id:id,p_po_number:po,p_notes:notes});if(r.error)return note(r.error.message,true);await loadPurchaseOrders();note("Purchase Order create ho gaya: "+po);}
async function loadPurchaseOrders(){const e=document.getElementById("purchaseOrders");if(!e||!user)return;const r=await sb.from("wholesale_purchase_orders").select("id,wholesale_order_id,po_number,notes,status,created_at").eq("buyer_id",user.id).order("created_at",{ascending:false}).limit(30);if(r.error){e.textContent=r.error.message;return}e.innerHTML=r.data?.length?r.data.map(x=>"<div class='card'><b>"+clean(x.po_number)+"</b><br>Status: "+clean(x.status)+"<br>"+clean(x.notes||"")+"</div>").join(""):"No purchase orders yet."}
async function repeatWholesaleOrder(id){if(!user)return note("Pehle login kijiye.",true);const sel=document.getElementById("wholesaleAddress");if(!sel||!sel.value)return note("Delivery address select kijiye.",true);const r=await sb.rpc("repeat_wholesale_order",{p_wholesale_order_id:id,p_address_id:sel.value});if(r.error)return note("Repeat order error: "+r.error.message,true);await loadWholesaleOrders();note("Repeat wholesale order create ho gaya. ID: "+r.data);}
async function printWholesaleInvoice(id){if(!user)return;const r=await sb.from("wholesale_orders").select("id,order_id,quantity,unit_price,total_amount,status,created_at,product_id").eq("id",id).eq("buyer_id",user.id).single();if(r.error)return note(r.error.message,true);const p=products.find(x=>x.id===r.data.product_id);const w=window.open("","_blank");if(!w)return note("Browser popup allow kijiye.",true);w.document.write("<!doctype html><html><head><title>ShubhMart Invoice</title><style>body{font-family:Arial;padding:30px}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ddd;padding:10px}</style></head><body><h1>ShubhMart</h1><h2>Wholesale Invoice</h2><p>Order: "+clean(r.data.order_id||r.data.id)+"<br>Date: "+new Date(r.data.created_at).toLocaleString()+"<br>Status: "+clean(r.data.status)+"</p><table><tr><th>Product</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr><tr><td>"+clean(p?.name||"Product")+"</td><td>"+r.data.quantity+"</td><td>₹"+Number(r.data.unit_price).toFixed(2)+"</td><td>₹"+Number(r.data.total_amount).toFixed(2)+"</td></tr></table><p><b>Total: ₹"+Number(r.data.total_amount).toFixed(2)+"</b></p><p>Payment: COD / Pending</p><script>window.print()<\/script></body></html>");w.document.close();}
async function acceptWholesaleInquiry(id){const r=await sb.rpc("buyer_update_wholesale_inquiry",{p_inquiry_id:id,p_status:"Accepted"});if(r.error)return note(r.error.message,true);await loadInquiries();note("Quote accepted.");}
async function cancelWholesaleInquiry(id){if(!confirm("Inquiry cancel karein?"))return;const r=await sb.rpc("buyer_update_wholesale_inquiry",{p_inquiry_id:id,p_status:"Cancelled"});if(r.error)return note(r.error.message,true);await loadInquiries();note("Inquiry cancelled.");}

async function loadBuyerAddresses(){const e=document.getElementById("addressBox");if(!e||!user)return;const r=await sb.from("addresses").select("id,name,house_shop,area,city,state,pincode,is_default").eq("customer_id",user.id).order("is_default",{ascending:false});if(r.error){e.textContent=r.error.message;return}e.innerHTML='<label>Delivery Address</label><select id="wholesaleAddress" style="width:100%;padding:11px;border:1px solid #ddd;border-radius:9px">'+(r.data||[]).map(a=>'<option value="'+a.id+'">'+clean(a.name)+' - '+clean([a.house_shop,a.area,a.city,a.state,a.pincode].filter(Boolean).join(", "))+(a.is_default?" (Default)":"")+'</option>').join("")+'</select>'+(r.data?.length?"":"<div class="small">Pehle Customer Store mein address add kijiye.</div>")}
async function createWholesaleOrder(id){if(!user)return note("Pehle login kijiye.",true);const sel=document.getElementById("wholesaleAddress");if(!sel||!sel.value)return note("Delivery address select kijiye.",true);const r=await sb.rpc("create_wholesale_order_from_quote",{p_inquiry_id:id,p_address_id:sel.value,p_payment_method:"cod"});if(r.error)return note("Bulk order error: "+r.error.message,true);await loadInquiries();note("Wholesale order create ho gaya. ID: "+r.data)}
