const sb=window.shubhSupabase;let user=null,products=[];
function note(t,bad){const e=document.getElementById("msg");e.className="msg "+(bad?"danger":"ok");e.textContent=t}
function clean(v){return String(v??"").replace(/[&<>"]/g,"")}
async function boot(){const r=await sb.auth.getUser();user=r.data.user||null;await loadWholesaleProducts();await loadInquiries()}
async function loadWholesaleProducts(){const term=document.getElementById("search").value.trim().toLowerCase();let q=sb.from("products").select("id,name,category,price,mrp,stock,image_url,description,seller_id").eq("status","Active").order("created_at",{ascending:false}).limit(60);const r=await q;if(r.error){document.getElementById("products").textContent=r.error.message;return}products=r.data||[];const ids=products.map(p=>p.id);let pricing=[];if(ids.length){const pr=await sb.from("wholesale_pricing").select("product_id,min_quantity,max_quantity,unit_price").eq("status","Active").in("product_id",ids).order("min_quantity",{ascending:true});pricing=pr.data||[]}const by={};pricing.forEach(x=>(by[x.product_id]??=[]).push(x));const filtered=products.filter(p=>!term||[p.name,p.category,p.description].join(" ").toLowerCase().includes(term));document.getElementById("products").innerHTML=filtered.length?filtered.map(p=>{const tiers=by[p.id]||[];return "<div class='card'>"+(p.image_url?"<img src='"+clean(p.image_url)+"' alt=''>":"")+"<h3>"+clean(p.name)+"</h3><div>"+clean(p.category||"")+"</div><p>Retail: ₹"+Number(p.price||0).toFixed(2)+"</p>"+(tiers.length?"<b>Bulk rates</b><div class='small'>"+tiers.map(t=>t.min_quantity+"+ pcs → ₹"+Number(t.unit_price).toFixed(2)+"/pc").join("<br>")+"</div>":"<div class='small'>Bulk quote available</div>")+"<button class='btn' onclick='openInquiry(""+p.id+"")'>Bulk Inquiry</button></div>"}).join(""):"No active wholesale products yet."}
async function openInquiry(id){if(!user){note("Bulk inquiry ke liye pehle Customer Store par login kijiye.",true);return}const p=products.find(x=>x.id===id);if(!p)return;const qty=Math.floor(Number(prompt("Kitni quantity chahiye?", "10")));if(!(qty>1))return note("Quantity 2 ya usse zyada honi chahiye.",true);const target=prompt("Aapka target price per piece? (optional)","");const noteText=prompt("Requirement / delivery note? (optional)","")||"";const r=await sb.from("wholesale_inquiries").insert({buyer_id:user.id,product_id:p.id,seller_id:p.seller_id,quantity:qty,target_price:target&&Number(target)>0?Number(target):null,note:noteText});if(r.error)return note("Inquiry error: "+r.error.message,true);note("Bulk inquiry seller ko bhej di gayi. Quotation aane par status yahan dikhega.");await loadInquiries()}
async function loadInquiries(){const e=document.getElementById("inquiries");if(!user){e.textContent="Login karke apni inquiries dekhein.";return}const r=await sb.from("wholesale_inquiries").select("id,product_id,quantity,target_price,quoted_price,status,note,created_at").eq("buyer_id",user.id).order("created_at",{ascending:false}).limit(30);if(r.error){e.textContent=r.error.message;return}const names={};(products||[]).forEach(p=>names[p.id]=p.name);e.innerHTML=r.data?.length?r.data.map(x=>{const action=x.status==="Quoted"?"<br><button class='btn' onclick='acceptWholesaleInquiry(\'"+x.id+"\')'>Accept Quote</button><button class='btn alt' onclick='cancelWholesaleInquiry(\'"+x.id+"\')'>Cancel</button>":"";return "<div class='card'><b>"+clean(names[x.product_id]||"Product")+"</b><br>Qty: "+x.quantity+" | Status: "+clean(x.status)+"<br>"+(x.quoted_price?"Seller quote: ₹"+Number(x.quoted_price).toFixed(2)+"/pc":"Waiting for seller quote")+action+"</div>"}).join(""):"No bulk inquiries yet."}
sb.auth.onAuthStateChange((event,session)=>{user=session?.user||null;setTimeout(loadInquiries,0)});boot();
async function saveBuyerBusinessProfile(){if(!user)return note("Pehle login kijiye.",true);const name=document.getElementById("buyerBusinessName").value.trim(),gst=document.getElementById("buyerGst").value.trim();if(!name)return note("Business name bhariye.",true);const r=await sb.from("profiles").update({full_name:name}).eq("id",user.id);if(r.error)return note(r.error.message,true);localStorage.setItem("shubhmart_buyer_business_"+user.id,JSON.stringify({name,gst}));note("Business profile saved.");}
async function acceptWholesaleInquiry(id){const r=await sb.rpc("buyer_update_wholesale_inquiry",{p_inquiry_id:id,p_status:"Accepted"});if(r.error)return note(r.error.message,true);await loadInquiries();note("Quote accepted.");}
async function cancelWholesaleInquiry(id){if(!confirm("Inquiry cancel karein?"))return;const r=await sb.rpc("buyer_update_wholesale_inquiry",{p_inquiry_id:id,p_status:"Cancelled"});if(r.error)return note(r.error.message,true);await loadInquiries();note("Inquiry cancelled.");}
