const sb=window.shubhSupabase;let adminUser=null;
function note(t,bad){const e=document.getElementById("msg");e.className="msg "+(bad?"danger":"ok");e.textContent=t}
function clean(v){return String(v??"").replace(/[&<>"']/g,"")}
async function loginAdmin(){const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value;if(!email||!password)return note("Email aur password bhariye.",true);const r=await sb.auth.signInWithPassword({email,password});if(r.error)return note(r.error.message,true);const p=await sb.from("profiles").select("role").eq("id",r.data.user.id).maybeSingle();if(p.error||p.data?.role!=="admin"){await sb.auth.signOut();return note("Is account ko Admin access nahi hai.",true)}adminUser=r.data.user;await showAdmin()}
async function showAdmin(){document.getElementById("login").classList.add("hidden");document.getElementById("admin").classList.remove("hidden");document.getElementById("logout").classList.remove("hidden");await Promise.all([loadStats(),loadSellers(),loadProducts(),loadOrders(),loadWholesalePricing(),loadWholesale(),loadDeliveryPartners(),loadShipments()])}
async function loadStats(){const [s,p,o,w]=await Promise.all([sb.from("Sellers").select("id",{count:"exact",head:true}),sb.from("products").select("id",{count:"exact",head:true}),sb.from("Orders").select("id",{count:"exact",head:true}),sb.from("wholesale_inquiries").select("id",{count:"exact",head:true})]);document.getElementById("stats").innerHTML=[["Sellers",s.count],["Products",p.count],["Orders",o.count],["Bulk Inquiries",w.count]].map(x=>"<div class='card'><b>"+x[0]+"</b><h2>"+(x[1]??0)+"</h2></div>").join("")}
async function loadSellers(){const r=await sb.from("Sellers").select("id,seller_name,shop_name,mobile,gst_number,status,kyc_status").order("created_at",{ascending:false}).limit(50);const e=document.getElementById("sellers");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(s=>"<div class='card'><b>"+clean(s.shop_name||s.seller_name)+"</b><br>"+clean(s.mobile||"")+" | KYC: "+clean(s.kyc_status||"Pending")+" | Account: "+clean(s.status||"Pending")+"<br><button class='btn' onclick=\"sellerStatus('"+s.id+"','Approved')\">Approve</button><button class='btn alt' onclick=\"sellerStatus('"+s.id+"','Rejected')\">Reject</button></div>").join(""):"No sellers yet."}
async function sellerStatus(id,status){const r=await sb.from("Sellers").update({status,approved_at:status==="Approved"?new Date().toISOString():null,rejection_reason:status==="Rejected"?"Rejected by admin":null}).eq("id",id);if(r.error)return note(r.error.message,true);note("Seller status updated.");await loadSellers()}
async function loadProducts(){const r=await sb.from("products").select("id,name,price,stock,status,seller_id").order("created_at",{ascending:false}).limit(80);const e=document.getElementById("products");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(p=>"<div class='card'><b>"+clean(p.name)+"</b><br>₹"+Number(p.price||0).toFixed(2)+" | Stock: "+Number(p.stock||0)+" | "+clean(p.status)+"<br><button class='btn' onclick=\"productStatus('"+p.id+"','Active')\">Approve</button><button class='btn alt' onclick=\"productStatus('"+p.id+"','Rejected')\">Reject</button></div>").join(""):"No products yet."}
async function productStatus(id,status){const r=await sb.from("products").update({status,approved_at:status==="Active"?new Date().toISOString():null,rejection_reason:status==="Rejected"?"Rejected by admin":null}).eq("id",id);if(r.error)return note(r.error.message,true);note("Product status updated.");await loadProducts()}
async function loadOrders(){const r=await sb.from("Orders").select("id,total_amount,order_status,payment_status,created_at").order("created_at",{ascending:false}).limit(50);const e=document.getElementById("orders");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(o=>"<div class='card'><b>Order "+clean(o.id.slice(0,8))+"…</b><br>₹"+Number(o.total_amount||0).toFixed(2)+" | "+clean(o.order_status)+" | "+clean(o.payment_status)+"</div>").join(""):"No orders yet."}
async function loadWholesalePricing(){const r=await sb.from("wholesale_pricing").select("id,min_quantity,max_quantity,unit_price,status,product_id,seller_id").order("created_at",{ascending:false}).limit(80);const e=document.getElementById("wholesalePricing");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(x=>"<div class='card'><b>MOQ "+x.min_quantity+(x.max_quantity?"–"+x.max_quantity:"+")+"</b> | ₹"+Number(x.unit_price).toFixed(2)+"/pc | "+clean(x.status)+"<br><button class='btn' onclick=\"pricingStatus('"+x.id+"','Active')\">Approve</button><button class='btn alt' onclick=\"pricingStatus('"+x.id+"','Rejected')\">Reject</button></div>").join(""):"No wholesale pricing submissions yet."}
async function pricingStatus(id,status){const r=await sb.from("wholesale_pricing").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(r.error)return note(r.error.message,true);note("Wholesale pricing status updated.");await loadWholesalePricing()}
async function loadWholesale(){const r=await sb.from("wholesale_inquiries").select("id,quantity,status,target_price,quoted_price,created_at").order("created_at",{ascending:false}).limit(50);const e=document.getElementById("wholesale");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(x=>"<div class='card'>Qty: "+x.quantity+" | Status: "+clean(x.status)+" | Quote: "+(x.quoted_price?"₹"+Number(x.quoted_price).toFixed(2):"—")+"</div>").join(""):"No bulk inquiries yet."}
async function logoutAdmin(){await sb.auth.signOut();location.reload()}
sb.auth.onAuthStateChange((event,session)=>{if(!session&&adminUser){adminUser=null;location.reload()}});
async function loadDeliveryPartners(){const e=document.getElementById("deliveryPartners");const r=await sb.from("delivery_partners").select("id,name,phone,vehicle_type,vehicle_number,status,availability").order("created_at",{ascending:false}).limit(50);if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(d=>"<div class='card'><b>"+clean(d.name)+"</b><br>"+clean(d.phone||"")+" | "+clean(d.vehicle_type||"")+" "+clean(d.vehicle_number||"")+"<br>Account: "+clean(d.status)+" | "+clean(d.availability)+"<br><button class='btn' onclick=\"partnerStatus('"+d.id+"','Approved')\">Approve</button><button class='btn alt' onclick=\"partnerStatus('"+d.id+"','Suspended')\">Suspend</button></div>").join(""):"No delivery partners yet."}
async function partnerStatus(id,status){const r=await sb.from("delivery_partners").update({status,availability:status==="Approved"?"Offline":"Offline",updated_at:new Date().toISOString()}).eq("id",id);if(r.error)return note(r.error.message,true);note("Delivery partner status updated.");await loadDeliveryPartners()}
async function createShipment(orderId){if(!orderId)return;const exists=await sb.from("shipments").select("id").eq("order_id",orderId).maybeSingle();if(exists.data)return note("Shipment already exists.");const tracking="SM"+Date.now().toString(36).toUpperCase();const r=await sb.from("shipments").insert({order_id:orderId,tracking_number:tracking,shipment_status:"Pending"}).select("id").single();if(r.error)return note(r.error.message,true);await sb.from("delivery_events").insert({shipment_id:r.data.id,status:"Pending",note:"Shipment created by admin",actor_user_id:adminUser.id});note("Shipment created: "+tracking);await loadShipments()}
async function assignShipment(id){const p=await sb.from("delivery_partners").select("id,name").eq("status","Approved").order("created_at",{ascending:true}).limit(20);if(p.error)return note(p.error.message,true);if(!p.data?.length)return note("Approved delivery partner nahi mila.",true);const list=p.data.map((x,i)=>i+" = "+x.name+" ("+x.id.slice(0,8)+")").join("\n");const pick=prompt("Partner number choose kijiye:\n"+list);const d=p.data[Number(pick)];if(!d)return;const r=await sb.from("shipments").update({delivery_partner_id:d.id,shipment_status:"Assigned",updated_at:new Date().toISOString()}).eq("id",id);if(r.error)return note(r.error.message,true);await sb.from("delivery_events").insert({shipment_id:id,status:"Assigned",note:"Assigned by admin",actor_user_id:adminUser.id});note("Shipment assigned.");await loadShipments()}
async function loadShipments(){const e=document.getElementById("shipments");const r=await sb.from("shipments").select("id,order_id,tracking_number,shipment_status,delivery_partner_id,estimated_delivery_at,created_at").order("created_at",{ascending:false}).limit(80);if(r.error)return e.textContent=r.error.message;const un=await sb.from("Orders").select("id,total_amount,order_status,created_at").order("created_at",{ascending:false}).limit(50);let ordersHtml=un.data?.filter(o=>!r.data?.some(s=>s.order_id===o.id)).map(o=>"<div class='card'><b>Order "+clean(o.id.slice(0,8))+"…</b> | ₹"+Number(o.total_amount||0).toFixed(2)+" | "+clean(o.order_status)+"<br><button class='btn' onclick=\"createShipment('"+o.id+"')\">Create Shipment</button></div>").join("")||"";let shipHtml=r.data?.map(s=>"<div class='card'><b>"+clean(s.tracking_number||"No tracking")+"</b> | Order "+clean(s.order_id.slice(0,8))+"…<br>Status: <b>"+clean(s.shipment_status)+"</b> | Partner: "+clean(s.delivery_partner_id?s.delivery_partner_id.slice(0,8):"Unassigned")+"<br><button class='btn' onclick=\"assignShipment('"+s.id+"')\">Assign / Reassign</button></div>").join("")||"";e.innerHTML="<h4>Existing Shipments</h4>"+shipHtml+"<h4>Orders awaiting shipment</h4>"+ordersHtml}
