const sb=window.shubhSupabase;let adminUser=null;
function note(t,bad){const e=document.getElementById("msg");e.className="msg "+(bad?"danger":"ok");e.textContent=t}
function clean(v){return String(v??"").replace(/[&<>"']/g,"")}
async function loginAdmin(){const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value;if(!email||!password)return note("Email aur password bhariye.",true);const r=await sb.auth.signInWithPassword({email,password});if(r.error)return note(r.error.message,true);const p=await sb.from("profiles").select("role").eq("id",r.data.user.id).maybeSingle();if(p.error||p.data?.role!=="admin"){await sb.auth.signOut();return note("Is account ko Admin access nahi hai.",true)}adminUser=r.data.user;await showAdmin()}
async function showAdmin(){document.getElementById("login").classList.add("hidden");document.getElementById("admin").classList.remove("hidden");document.getElementById("logout").classList.remove("hidden");await Promise.all([loadStats(),loadSellers(),loadProducts(),loadOrders(),loadWholesalePricing(),loadWholesale(),loadWholesaleOrders(),loadUsers(),loadAuditLogs(),loadRiskFlags(),loadFeatureFlags(),loadDeliveryPartners(),loadShipments(),loadServiceProviders(),loadServicesAdmin(),loadServiceBookings(),loadCreditApplications(),loadReturns(),loadRefunds(),loadSellerPayouts(),loadBuyerProtection(),loadNotifications(),loadSupportTickets()])}
async function loadStats(){const [s,p,o,w]=await Promise.all([sb.from("Sellers").select("id",{count:"exact",head:true}),sb.from("products").select("id",{count:"exact",head:true}),sb.from("Orders").select("id",{count:"exact",head:true}),sb.from("wholesale_inquiries").select("id",{count:"exact",head:true})]);document.getElementById("stats").innerHTML=[["Sellers",s.count],["Products",p.count],["Orders",o.count],["Bulk Inquiries",w.count]].map(x=>"<div class='card'><b>"+x[0]+"</b><h2>"+(x[1]??0)+"</h2></div>").join("")}
async function loadSellers(){const r=await sb.from("Sellers").select("id,seller_name,shop_name,mobile,gst_number,status,kyc_status").order("created_at",{ascending:false}).limit(50);const e=document.getElementById("sellers");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(s=>"<div class='card'><b>"+clean(s.shop_name||s.seller_name)+"</b><br>"+clean(s.mobile||"")+" | KYC: "+clean(s.kyc_status||"Pending")+" | Account: "+clean(s.status||"Pending")+"<br><button class='btn' onclick=\"sellerStatus('"+s.id+"','Approved')\">Approve</button><button class='btn alt' onclick=\"sellerStatus('"+s.id+"','Rejected')\">Reject</button></div>").join(""):"No sellers yet."}
async function sellerStatus(id,status){const r=await sb.rpc("admin_set_seller_status",{p_seller_id:id,p_status:status});if(r.error)return note(r.error.message,true);note("Seller status updated.");await loadSellers();await loadAuditLogs()}
async function loadProducts(){const r=await sb.from("products").select("id,name,price,stock,status,seller_id").order("created_at",{ascending:false}).limit(80);const e=document.getElementById("products");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(p=>"<div class='card'><b>"+clean(p.name)+"</b><br>₹"+Number(p.price||0).toFixed(2)+" | Stock: "+Number(p.stock||0)+" | "+clean(p.status)+"<br><button class='btn' onclick=\"productStatus('"+p.id+"','Active')\">Approve</button><button class='btn alt' onclick=\"productStatus('"+p.id+"','Rejected')\">Reject</button></div>").join(""):"No products yet."}
async function productStatus(id,status){const r=await sb.rpc("admin_set_product_status",{p_product_id:id,p_status:status});if(r.error)return note(r.error.message,true);note("Product status updated.");await loadProducts();await loadAuditLogs()}
async function loadOrders(){const r=await sb.from("Orders").select("id,total_amount,order_status,payment_status,payment_method,customer_name,customer_phone,created_at").order("created_at",{ascending:false}).limit(100);const e=document.getElementById("orders");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(o=>`<div class="card"><b>Order ${clean(o.id.slice(0,8))}…</b><br>${clean(o.customer_name||"Customer")} | ${clean(o.customer_phone||"")}<br>₹${Number(o.total_amount||0).toFixed(2)} | ${clean(o.payment_method)} | Payment: ${clean(o.payment_status)} | Order: ${clean(o.order_status)}<br><button class="btn" onclick="orderStatus('${o.id}','Confirmed')">Confirm</button><button class="btn" onclick="orderStatus('${o.id}','Processing')">Process</button><button class="btn" onclick="orderStatus('${o.id}','Packed')">Packed</button><button class="btn" onclick="orderStatus('${o.id}','Dispatched')">Dispatch</button><button class="btn" onclick="orderStatus('${o.id}','Delivered')">Delivered</button><button class="btn alt" onclick="orderStatus('${o.id}','Cancelled')">Cancel</button></div>`).join(""):"No orders yet."}
async function orderStatus(id,status){const n=prompt("Admin note (optional):","")||"";const r=await sb.rpc("admin_update_order_status",{p_order_id:id,p_status:status,p_note:n});if(r.error)return note(r.error.message,true);note("Order status updated.");await loadOrders();await loadAuditLogs()}
function csv(rows){if(!rows?.length)return "";const keys=Object.keys(rows[0]);return [keys.join(","),...rows.map(x=>keys.map(k=>{const v=String(x[k]??"");return '"' + v.replace(/"/g,'""') + '"' ;}).join(","))].join("\n")}
function downloadCSV(name,rows){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv(rows)],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function exportOrdersCSV(){const r=await sb.from("Orders").select("id,customer_name,customer_phone,total_amount,payment_method,payment_status,order_status,created_at").order("created_at",{ascending:false}).limit(5000);if(r.error)return note(r.error.message,true);downloadCSV("shubhmart-orders.csv",r.data||[]);note("Orders CSV ready.")}
async function exportPayoutsCSV(){const r=await sb.from("payouts").select("id,seller_id,amount,status,payout_reference,requested_at,paid_at").order("requested_at",{ascending:false}).limit(5000);if(r.error)return note(r.error.message,true);downloadCSV("shubhmart-seller-payouts.csv",r.data||[]);note("Payouts CSV ready.")}
async function loadWholesalePricing(){const r=await sb.from("wholesale_pricing").select("id,min_quantity,max_quantity,unit_price,status,product_id,seller_id").order("created_at",{ascending:false}).limit(80);const e=document.getElementById("wholesalePricing");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(x=>"<div class='card'><b>MOQ "+x.min_quantity+(x.max_quantity?"–"+x.max_quantity:"+")+"</b> | ₹"+Number(x.unit_price).toFixed(2)+"/pc | "+clean(x.status)+"<br><button class='btn' onclick=\"pricingStatus('"+x.id+"','Active')\">Approve</button><button class='btn alt' onclick=\"pricingStatus('"+x.id+"','Rejected')\">Reject</button></div>").join(""):"No wholesale pricing submissions yet."}
async function pricingStatus(id,status){const r=await sb.rpc("admin_set_wholesale_pricing_status",{p_pricing_id:id,p_status:status});if(r.error)return note(r.error.message,true);note("Wholesale pricing status updated.");await loadWholesalePricing();await loadAuditLogs()}
async function loadWholesale(){const r=await sb.from("wholesale_inquiries").select("id,quantity,status,target_price,quoted_price,created_at").order("created_at",{ascending:false}).limit(50);const e=document.getElementById("wholesale");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(x=>"<div class='card'>Qty: "+x.quantity+" | Status: "+clean(x.status)+" | Quote: "+(x.quoted_price?"₹"+Number(x.quoted_price).toFixed(2):"—")+"</div>").join(""):"No bulk inquiries yet."}
async function logoutAdmin(){await sb.auth.signOut();location.reload()}
sb.auth.onAuthStateChange((event,session)=>{if(!session&&adminUser){adminUser=null;location.reload()}});
async function loadDeliveryPartners(){const e=document.getElementById("deliveryPartners");const r=await sb.from("delivery_partners").select("id,name,phone,vehicle_type,vehicle_number,status,availability").order("created_at",{ascending:false}).limit(50);if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(d=>"<div class='card'><b>"+clean(d.name)+"</b><br>"+clean(d.phone||"")+" | "+clean(d.vehicle_type||"")+" "+clean(d.vehicle_number||"")+"<br>Account: "+clean(d.status)+" | "+clean(d.availability)+"<br><button class='btn' onclick=\"partnerStatus('"+d.id+"','Approved')\">Approve</button><button class='btn alt' onclick=\"partnerStatus('"+d.id+"','Suspended')\">Suspend</button></div>").join(""):"No delivery partners yet."}
async function partnerStatus(id,status){const r=await sb.rpc("admin_set_delivery_partner_status",{p_partner_id:id,p_status:status});if(r.error)return note(r.error.message,true);note("Delivery partner status updated.");await loadDeliveryPartners();await loadAuditLogs()}
async function createShipment(orderId){if(!orderId)return;const r=await sb.rpc("admin_create_shipment",{p_order_id:orderId});if(r.error)return note(r.error.message,true);note("Shipment created.");await loadShipments();await loadAuditLogs()}
async function assignShipment(id){const p=await sb.from("delivery_partners").select("id,name").eq("status","Approved").order("created_at",{ascending:true}).limit(20);if(p.error)return note(p.error.message,true);if(!p.data?.length)return note("Approved delivery partner nahi mila.",true);const list=p.data.map((x,i)=>i+" = "+x.name+" ("+x.id.slice(0,8)+")").join("
");const pick=prompt("Partner number choose kijiye:
"+list);const d=p.data[Number(pick)];if(!d)return;const r=await sb.rpc("admin_assign_shipment",{p_shipment_id:id,p_partner_id:d.id});if(r.error)return note(r.error.message,true);note("Shipment assigned.");await loadShipments();await loadAuditLogs()}
async function loadShipments(){const e=document.getElementById("shipments");const r=await sb.from("shipments").select("id,order_id,tracking_number,shipment_status,delivery_partner_id,estimated_delivery_at,created_at").order("created_at",{ascending:false}).limit(80);if(r.error)return e.textContent=r.error.message;const un=await sb.from("Orders").select("id,total_amount,order_status,created_at").order("created_at",{ascending:false}).limit(50);let ordersHtml=un.data?.filter(o=>!r.data?.some(s=>s.order_id===o.id)).map(o=>"<div class='card'><b>Order "+clean(o.id.slice(0,8))+"…</b> | ₹"+Number(o.total_amount||0).toFixed(2)+" | "+clean(o.order_status)+"<br><button class='btn' onclick=\"createShipment('"+o.id+"')\">Create Shipment</button></div>").join("")||"";let shipHtml=r.data?.map(s=>"<div class='card'><b>"+clean(s.tracking_number||"No tracking")+"</b> | Order "+clean(s.order_id.slice(0,8))+"…<br>Status: <b>"+clean(s.shipment_status)+"</b> | Partner: "+clean(s.delivery_partner_id?s.delivery_partner_id.slice(0,8):"Unassigned")+"<br><button class='btn' onclick=\"assignShipment('"+s.id+"')\">Assign / Reassign</button></div>").join("")||"";e.innerHTML="<h4>Existing Shipments</h4>"+shipHtml+"<h4>Orders awaiting shipment</h4>"+ordersHtml}

async function loadServiceProviders(){const e=document.getElementById("serviceProviders");const r=await sb.from("service_providers").select("id,name,business_name,category,service_area,status,kyc_status").order("created_at",{ascending:false}).limit(50);if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.map(x=>"<div class='card'><b>"+clean(x.business_name||x.name)+"</b><br>"+clean(x.category||"")+" | "+clean(x.service_area||"")+" | KYC "+clean(x.kyc_status)+" | "+clean(x.status)+"<br><button class='btn' onclick=\"serviceProviderStatus('"+x.id+"','Approved')\">Approve</button><button class='btn alt' onclick=\"serviceProviderStatus('"+x.id+"','Rejected')\">Reject</button></div>").join("")||"No service providers."}async function serviceProviderStatus(id,status){const r=await sb.rpc("admin_set_service_provider_status",{p_provider_id:id,p_status:status});if(r.error)return note(r.error.message,true);note("Service provider status updated.");await loadServiceProviders();await loadAuditLogs()}async function loadServicesAdmin(){const e=document.getElementById("services");const r=await sb.from("services").select("id,name,category,price,status,provider_id").order("created_at",{ascending:false}).limit(80);if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.map(x=>"<div class='card'><b>"+clean(x.name)+"</b> | "+clean(x.category)+" | ₹"+Number(x.price||0).toFixed(0)+" | "+clean(x.status)+"<br><button class='btn' onclick=\"serviceStatus('"+x.id+"','Active')\">Approve</button><button class='btn alt' onclick=\"serviceStatus('"+x.id+"','Rejected')\">Reject</button></div>").join("")||"No services."}async function serviceStatus(id,status){const r=await sb.rpc("admin_set_service_status",{p_service_id:id,p_status:status});if(r.error)return note(r.error.message,true);note("Service status updated.");await loadServicesAdmin();await loadAuditLogs()}async function loadServiceBookings(){const e=document.getElementById("serviceBookings");const r=await sb.from("service_bookings").select("id,booking_status,payment_status,total_amount,created_at,services(name)").order("created_at",{ascending:false}).limit(80);if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.map(x=>"<div class='card'><b>"+clean(x.services?.name||"Service")+"</b> | ₹"+Number(x.total_amount||0).toFixed(0)+"<br>"+clean(x.booking_status)+" | "+clean(x.payment_status)+"</div>").join("")||"No service bookings."}
async function loadCreditApplications(){const e=document.getElementById("creditApplications");if(!e)return;const r=await sb.from("shubhcredit_applications").select("id,customer_id,requested_limit,monthly_income,employment_type,status,created_at").order("created_at",{ascending:false}).limit(100);if(r.error){e.textContent=r.error.message;return;}e.innerHTML=r.data?.map(x=>`<div class="card"><b>₹${Number(x.requested_limit||0).toFixed(0)}</b> | Income ₹${Number(x.monthly_income||0).toFixed(0)} | ${clean(x.employment_type||"")}<br>Status: ${clean(x.status)}<br><button class="btn" onclick="creditAppStatus('${x.id}','Under Review')">Review</button><button class="btn" onclick="creditAppStatus('${x.id}','Approved')">Approve</button><button class="btn alt" onclick="creditAppStatus('${x.id}','Rejected')">Reject</button></div>`).join("")||"No credit applications."}async function creditAppStatus(id,status){const r=await sb.rpc("admin_set_credit_application_status",{p_application_id:id,p_status:status});if(r.error)return note(r.error.message,true);note("Credit application updated.");await loadCreditApplications();await loadAuditLogs()}
async function loadReturns(){const e=document.getElementById("returns");if(!e)return;const r=await sb.from("returns").select("id,order_id,customer_id,status,return_type,refund_amount,refund_status,pickup_status,reason,created_at").order("created_at",{ascending:false}).limit(100);if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.map(x=>"<div class='card'><b>Order "+clean(x.order_id.slice(0,8))+"…</b> | "+clean(x.return_type)+" | "+clean(x.status)+"<br>Refund ₹"+Number(x.refund_amount||0).toFixed(2)+" | "+clean(x.refund_status)+" | Pickup "+clean(x.pickup_status)+"<br>"+clean(x.reason||"")+"<br><button class='btn' onclick=\"returnStatus('"+x.id+"','Approved',"+Number(x.refund_amount||0)+")\">Approve</button><button class='btn' onclick=\"returnStatus('"+x.id+"','Pickup Scheduled',"+Number(x.refund_amount||0)+")\">Schedule Pickup</button><button class='btn' onclick=\"returnStatus('"+x.id+"','Pickup Completed',"+Number(x.refund_amount||0)+")\">Pickup Done</button><button class='btn' onclick=\"returnStatus('"+x.id+"','Refund Pending',"+Number(x.refund_amount||0)+")\">Create Refund</button><button class='btn alt' onclick=\"returnStatus('"+x.id+"','Rejected',0)\">Reject</button></div>").join("")||"No return requests."}
async function returnStatus(id,status,amount){const r=await sb.rpc("admin_update_return_status",{p_return_id:id,p_status:status,p_refund_amount:Number(amount||0),p_note:"Admin action"});if(r.error)return note(r.error.message,true);note("Return status updated.");await loadReturns();await loadRefunds()}
async function loadRefunds(){const e=document.getElementById("refunds");if(!e)return;const r=await sb.from("refunds").select("id,order_id,return_id,amount,status,method,gateway_ref,created_at").order("created_at",{ascending:false}).limit(100);if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.map(x=>"<div class='card'><b>Order "+clean(x.order_id.slice(0,8))+"…</b> | ₹"+Number(x.amount||0).toFixed(2)+" | "+clean(x.status)+" | "+clean(x.method)+"<br>Gateway Ref: "+clean(x.gateway_ref||"—")+"<br><button class='btn' onclick=\"finalizeRefund('"+x.id+"')\">Mark Refund Completed</button></div>").join("")||"No refund records."}
async function finalizeRefund(id){const ref=prompt("Actual gateway/bank refund transaction reference dijiye:");if(!ref)return;const r=await sb.rpc("admin_finalize_refund",{p_refund_id:id,p_gateway_ref:ref,p_notes:"Refund reference verified by admin"});if(r.error)return note(r.error.message,true);note("Refund recorded as Completed. Actual money transfer must be confirmed with gateway/bank reference.");await loadRefunds();await loadReturns()}
async function loadBuyerProtection(){const e=document.getElementById("buyerProtection");if(!e)return;const r=await sb.from("buyer_protection_claims").select("id,order_id,customer_id,reason,description,status,created_at").order("created_at",{ascending:false}).limit(100);if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.map(x=>"<div class='card'><b>Order "+clean(x.order_id.slice(0,8))+"…</b> | "+clean(x.status)+"<br>"+clean(x.reason)+"<br>"+clean(x.description||"")+"<br><button class='btn' onclick=\"claimStatus('"+x.id+"','Under Review')\">Review</button><button class='btn' onclick=\"claimStatus('"+x.id+"','Approved')\">Approve</button><button class='btn' onclick=\"claimStatus('"+x.id+"','Resolved')\">Resolve</button><button class='btn alt' onclick=\"claimStatus('"+x.id+"','Rejected')\">Reject</button></div>").join("")||"No buyer protection claims."}
async function claimStatus(id,status){let resolution=null;if(status==="Resolved")resolution=prompt("Resolution note:","Resolved by admin")||"";const r=await sb.rpc("admin_update_buyer_protection_claim",{p_claim_id:id,p_status:status,p_resolution:resolution});if(r.error)return note(r.error.message,true);note("Buyer Protection claim updated.");await loadBuyerProtection();await loadAuditLogs()}

async function loadNotifications(){const e=document.getElementById("notifications");if(!e)return;const r=await sb.from("notifications").select("id,user_id,title,body,type,is_read,created_at").order("created_at",{ascending:false}).limit(100);if(r.error)return e.textContent=r.error.message;e.innerHTML=(r.data||[]).map(x=>"<div class='card'><b>"+clean(x.title)+"</b> | "+clean(x.type)+" | "+(x.is_read?"Read":"Unread")+"<br>"+clean(x.body)+"</div>").join("")||"No notifications."}
async function loadSupportTickets(){const e=document.getElementById("supportTickets");if(!e)return;const r=await sb.from("support_tickets").select("id,user_id,order_id,subject,category,message,status,priority,created_at").order("created_at",{ascending:false}).limit(100);if(r.error)return e.textContent=r.error.message;e.innerHTML=(r.data||[]).map(x=>`<div class="card"><b>${clean(x.subject)}</b> | ${clean(x.category)} | ${clean(x.priority)} | ${clean(x.status)}<br>${clean(x.message)}<br><button class="btn" onclick="ticketStatus('${x.id}','In Progress')">Take Up</button><button class="btn" onclick="ticketStatus('${x.id}','Waiting for Customer')">Waiting</button><button class="btn" onclick="ticketStatus('${x.id}','Resolved')">Resolve</button><button class="btn alt" onclick="ticketStatus('${x.id}','Closed')">Close</button></div>`).join("")||"No support tickets."}
async function ticketStatus(id,status){const noteText=prompt("Admin note (optional):","")||"";const r=await sb.rpc("admin_update_support_ticket",{p_ticket_id:id,p_status:status,p_priority:"Normal",p_admin_note:noteText});if(r.error)return note(r.error.message,true);note("Support ticket updated.");await loadSupportTickets()}

async function loadSellerPayouts(){const e=document.getElementById("sellerPayouts");if(!e)return;const r=await sb.from("payouts").select("id,seller_id,amount,status,payout_reference,requested_at,paid_at").order("requested_at",{ascending:false}).limit(100);if(r.error)return e.textContent=r.error.message;e.innerHTML=(r.data||[]).map(x=>"<div class='card'><b>₹"+Number(x.amount||0).toFixed(2)+"</b> | Seller "+clean(x.seller_id.slice(0,8))+"… | "+clean(x.status)+"<br>Ref: "+clean(x.payout_reference||"—")+"<br><button class='btn' onclick=\"sellerPayoutStatus('"+x.id+"','Processing')\">Processing</button><button class='btn' onclick=\"sellerPayoutStatus('"+x.id+"','Paid')\">Mark Paid</button><button class='btn alt' onclick=\"sellerPayoutStatus('"+x.id+"','Rejected')\">Reject</button></div>").join("")||"No seller payout requests."}
async function sellerPayoutStatus(id,status){let ref=null;if(status==="Paid"){ref=prompt("Actual bank/UPI/gateway payout reference dijiye:");if(!ref)return;}const r=await sb.rpc("admin_update_seller_payout",{p_payout_id:id,p_status:status,p_reference:ref});if(r.error)return note(r.error.message,true);note("Seller payout status updated.");await loadSellerPayouts()}

async function loadWholesaleOrders(){const e=document.getElementById("wholesaleOrders");if(!e)return;const r=await sb.from("wholesale_orders").select("id,order_id,buyer_id,seller_id,quantity,unit_price,total_amount,status,created_at").order("created_at",{ascending:false}).limit(100);if(r.error)return e.textContent=r.error.message;e.innerHTML=(r.data||[]).map(x=>"<div class='card'><b>"+clean(x.order_id||x.id)+"</b><br>Qty "+x.quantity+" × ₹"+Number(x.unit_price).toFixed(2)+" = ₹"+Number(x.total_amount).toFixed(2)+"<br>Status: "+clean(x.status)+"</div>").join("")||"No wholesale orders."}
async function loadUsers(){const e=document.getElementById("users");if(!e)return;const r=await sb.from("profiles").select("id,full_name,phone,role,created_at").order("created_at",{ascending:false}).limit(100);if(r.error)return e.textContent=r.error.message;e.innerHTML=(r.data||[]).map(x=>"<div class='card'><b>"+clean(x.full_name||"Unnamed")+"</b><br>"+clean(x.phone||"")+" | Role: "+clean(x.role)+" | "+new Date(x.created_at).toLocaleString()+"</div>").join("")||"No users."}
async function loadAuditLogs(){const e=document.getElementById("auditLogs");if(!e)return;const r=await sb.from("admin_audit_logs").select("id,action,entity_type,entity_id,metadata,created_at").order("created_at",{ascending:false}).limit(100);if(r.error)return e.textContent=r.error.message;e.innerHTML=(r.data||[]).map(x=>"<div class='card'><b>"+clean(x.action)+"</b> | "+clean(x.entity_type)+" | "+clean(x.entity_id)+"<br>"+clean(JSON.stringify(x.metadata||{}))+"<br>"+new Date(x.created_at).toLocaleString()+"</div>").join("")||"No admin audit events yet."}

async function loadRiskFlags(){const e=document.getElementById("riskFlags");if(!e)return;const r=await sb.from("risk_flags").select("id,entity_type,entity_id,risk_level,reason,status,created_at").order("created_at",{ascending:false}).limit(100);if(r.error)return e.textContent=r.error.message;e.innerHTML=(r.data||[]).map(x=>"<div class='card'><b>"+clean(x.risk_level)+"</b> | "+clean(x.entity_type)+" | "+clean(x.reason)+"<br>Status: "+clean(x.status)+" | "+new Date(x.created_at).toLocaleString()+"<br><button class='btn' onclick="riskStatus('"+x.id+"','Investigating')">Investigate</button><button class='btn' onclick="riskStatus('"+x.id+"','Resolved')">Resolve</button><button class='btn alt' onclick="riskStatus('"+x.id+"','Dismissed')">Dismiss</button></div>").join("")||"No risk flags."}
async function riskStatus(id,status){const r=await sb.rpc("admin_set_risk_flag_status",{p_id:id,p_status:status});if(r.error)return note(r.error.message,true);note("Risk flag updated.");await loadRiskFlags();await loadAuditLogs()}
async function loadFeatureFlags(){const e=document.getElementById("featureFlags");if(!e)return;const r=await sb.from("feature_flags").select("key,enabled,description,updated_at").order("key");if(r.error)return e.textContent=r.error.message;e.innerHTML=(r.data||[]).map(x=>"<div class='card'><b>"+clean(x.key)+"</b><br>"+clean(x.description||"")+"<br>Status: <b>"+(x.enabled?"ON":"OFF")+"</b> <button class='btn' onclick="featureFlag('"+x.key+"',"+(!x.enabled)+")">Turn "+(x.enabled?"OFF":"ON")+"</button></div>").join("")||"No feature flags."}
async function featureFlag(key,enabled){const r=await sb.rpc("admin_set_feature_flag",{p_key:key,p_enabled:enabled});if(r.error)return note(r.error.message,true);note("Feature flag updated.");await loadFeatureFlags();await loadAuditLogs()}
