const sb=window.shubhSupabase;let adminUser=null;
function note(t,bad){const e=document.getElementById("msg");e.className="msg "+(bad?"danger":"ok");e.textContent=t}
function clean(v){return String(v??"").replace(/[&<>"']/g,"")}
async function loginAdmin(){const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value;if(!email||!password)return note("Email aur password bhariye.",true);const r=await sb.auth.signInWithPassword({email,password});if(r.error)return note(r.error.message,true);const p=await sb.from("profiles").select("role").eq("id",r.data.user.id).maybeSingle();if(p.error||p.data?.role!=="admin"){await sb.auth.signOut();return note("Is account ko Admin access nahi hai.",true)}adminUser=r.data.user;showAdmin()}
async function showAdmin(){document.getElementById("login").classList.add("hidden");document.getElementById("admin").classList.remove("hidden");document.getElementById("logout").classList.remove("hidden");await Promise.all([loadStats(),loadSellers(),loadProducts(),loadOrders(),loadWholesalePricing(),loadWholesale()])}
async function loadStats(){const [s,p,o,w]=await Promise.all([sb.from("Sellers").select("id",{count:"exact",head:true}),sb.from("products").select("id",{count:"exact",head:true}),sb.from("Orders").select("id",{count:"exact",head:true}),sb.from("wholesale_inquiries").select("id",{count:"exact",head:true})]);document.getElementById("stats").innerHTML=[["Sellers",s.count],["Products",p.count],["Orders",o.count],["Bulk Inquiries",w.count]].map(x=>"<div class='card'><b>"+x[0]+"</b><h2>"+(x[1]??0)+"</h2></div>").join("")}
async function loadSellers(){const r=await sb.from("Sellers").select("id,seller_name,shop_name,mobile,gst_number,status,kyc_status").order("created_at",{ascending:false}).limit(50);const e=document.getElementById("sellers");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(s=>"<div class='card'><b>"+clean(s.shop_name||s.seller_name)+"</b><br>"+clean(s.mobile||"")+" | KYC: "+clean(s.kyc_status||"Pending")+" | Account: "+clean(s.status||"Pending")+"<br><button class='btn' onclick='sellerStatus(""+s.id+"","Approved")'>Approve</button><button class='btn alt' onclick='sellerStatus(""+s.id+"","Rejected")'>Reject</button></div>").join(""):"No sellers yet."}
async function sellerStatus(id,status){const r=await sb.from("Sellers").update({status,approved_at:status==="Approved"?new Date().toISOString():null,rejection_reason:status==="Rejected"?"Rejected by admin":null}).eq("id",id);if(r.error)return note(r.error.message,true);note("Seller status updated.");loadSellers()}
async function loadProducts(){const r=await sb.from("products").select("id,name,price,stock,status,seller_id").order("created_at",{ascending:false}).limit(80);const e=document.getElementById("products");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(p=>"<div class='card'><b>"+clean(p.name)+"</b><br>₹"+Number(p.price||0).toFixed(2)+" | Stock: "+Number(p.stock||0)+" | "+clean(p.status)+"<br><button class='btn' onclick='productStatus(""+p.id+"","Active")'>Approve</button><button class='btn alt' onclick='productStatus(""+p.id+"","Rejected")'>Reject</button></div>").join(""):"No products yet."}
async function productStatus(id,status){const r=await sb.from("products").update({status,approved_at:status==="Active"?new Date().toISOString():null,rejection_reason:status==="Rejected"?"Rejected by admin":null}).eq("id",id);if(r.error)return note(r.error.message,true);note("Product status updated.");loadProducts()}
async function loadOrders(){const r=await sb.from("Orders").select("id,total_amount,order_status,payment_status,created_at").order("created_at",{ascending:false}).limit(50);const e=document.getElementById("orders");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(o=>"<div class='card'><b>Order "+clean(o.id.slice(0,8))+"…</b><br>₹"+Number(o.total_amount||0).toFixed(2)+" | "+clean(o.order_status)+" | "+clean(o.payment_status)+"</div>").join(""):"No orders yet."}
async function loadWholesale(){const r=await sb.from("wholesale_inquiries").select("id,quantity,status,target_price,quoted_price,created_at").order("created_at",{ascending:false}).limit(50);const e=document.getElementById("wholesale");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(x=>"<div class='card'>Qty: "+x.quantity+" | Status: "+clean(x.status)+" | Quote: "+(x.quoted_price?"₹"+Number(x.quoted_price).toFixed(2):"—")+"</div>").join(""):"No bulk inquiries yet."}
async function logoutAdmin(){await sb.auth.signOut();location.reload()}
sb.auth.onAuthStateChange((event,session)=>{if(!session&&adminUser){adminUser=null;location.reload()}});\nasync function loadWholesalePricing(){const r=await sb.from("wholesale_pricing").select("id,min_quantity,max_quantity,unit_price,status,product_id,seller_id").order("created_at",{ascending:false}).limit(80);const e=document.getElementById("wholesalePricing");if(r.error)return e.textContent=r.error.message;e.innerHTML=r.data?.length?r.data.map(x=>"<div class=\"card\"><b>MOQ "+x.min_quantity+(x.max_quantity?"–"+x.max_quantity:"+")+"</b> | ₹"+Number(x.unit_price).toFixed(2)+"/pc | "+clean(x.status)+"<br><button class=\"btn\" onclick=\"pricingStatus(\\\""+x.id+"\\\",\\\"Active\\\")\">Approve</button><button class=\"btn alt\" onclick=\"pricingStatus(\\\""+x.id+"\\\",\\\"Rejected\\\")\">Reject</button></div>").join(""):"No wholesale pricing submissions yet."}\nasync function pricingStatus(id,status){const r=await sb.from("wholesale_pricing").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(r.error)return note(r.error.message,true);note("Wholesale pricing status updated.");loadWholesalePricing()}