const PAYMENT_FUNCTION = "razorpay-payment";
const sb = window.shubhSupabase;

let currentUser = null;
let selectedAddress = null;
let checkoutBusy = false;
let checkoutReviewReady = false;

/* MESSAGE */
function note(text,danger=false){const e=document.getElementById("msg");if(!e)return;e.className=danger?"msg danger":"msg";e.textContent=text;setTimeout(()=>e.textContent="",4000);}

/* NAVIGATION */
function show(id){["home","cart","orders","account"].forEach(x=>document.getElementById(x)?.classList.toggle("hidden",x!==id));if(id==="cart")loadCart();if(id==="orders")loadOrders();if(id==="account")loadAccount();}

/* ESCAPE */
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}

/* PRODUCTS */
async function loadProducts(){const q=document.getElementById("search")?.value.trim(),cat=document.getElementById("categoryFilter")?.value||"",sort=document.getElementById("sortFilter")?.value||"newest";let query=sb.from("products").select("id,name,category,price,mrp,stock,image_url,description,seller_id,created_at").eq("status","Active");if(q)query=query.or("name.ilike.%"+q+"%,category.ilike.%"+q+"%,description.ilike.%"+q+"%");if(cat)query=query.eq("category",cat);if(sort==="price_low")query=query.order("price",{ascending:true});else if(sort==="price_high")query=query.order("price",{ascending:false});else if(sort==="name")query=query.order("name",{ascending:true});else query=query.order("created_at",{ascending:false});const {data,error}=await query.limit(100);const el=document.getElementById("products");if(error){el.innerHTML="<div>Products load error: "+esc(error.message)+"</div>";return;}const cats=[...new Set((data||[]).map(p=>p.category).filter(Boolean))].sort();const sel=document.getElementById("categoryFilter");if(sel){const current=sel.value;sel.innerHTML='<option value="">All Categories</option>'+cats.map(c=>'<option value="'+esc(c)+'">'+esc(c)+'</option>').join("");if(cats.includes(current))sel.value=current;}if(!data?.length){el.innerHTML="No matching active products.";return;}el.innerHTML=data.map(p=>`<div class="card" onclick="recordRecentlyViewed('${p.id}')"><img src="${esc(p.image_url||"https://placehold.co/500x400?text=ShubhMart")}" alt="${esc(p.name)}"><h3>${esc(p.name)}</h3><div class="price">₹${Number(p.price||0).toFixed(0)} <span class="old">₹${Number(p.mrp||0).toFixed(0)}</span></div><div class="small">${esc(p.category||"")} · Stock: ${Math.max(0,Number(p.stock||0))}</div><button class="btn" onclick="event.stopPropagation();addCart('${p.id}')">Add to Cart</button><button class="btn alt" onclick="event.stopPropagation();buy('${p.id}')">Buy Now</button><button class="btn alt" onclick="event.stopPropagation();toggleWishlist('${p.id}')">❤️</button><button class="btn alt" onclick="event.stopPropagation();toggleCompare('${p.id}')">⚖️</button><button class="btn alt" onclick="event.stopPropagation();showProductDetail('${p.id}')">View</button></div>`).join("");}

/* CART BADGE */
async function updateCartBadge(){const badge=document.getElementById("cartBadge");if(!badge)return;if(!currentUser){badge.textContent="0";return;}const {data,error}=await sb.from("cart").select("quantity").eq("customer_id",currentUser.id);if(error){badge.textContent="0";return;}badge.textContent=String((data||[]).reduce((n,row)=>n+Number(row.quantity||0),0));}

/* CART */
async function addCart(id){if(!currentUser){note("Pehle login/signup kijiye",true);show("account");return;}const {error}=await sb.from("cart").upsert({customer_id:currentUser.id,product_id:id,quantity:1},{onConflict:"customer_id,product_id"});if(error)note(error.message,true);else{note("Cart mein add ho gaya ✅");await updateCartBadge();}}
async function buy(id){if(!currentUser){note("Pehle login/signup kijiye",true);show("account");return;}await addCart(id);show("cart");}

async function loadCart(){if(!currentUser){document.getElementById("cartbox").innerHTML="Login kijiye.";return;}const {data,error}=await sb.from("cart").select("id,quantity,product_id,products(id,name,price,mrp,image_url,category,seller_id,Sellers(id,shop_name,seller_name))").eq("customer_id",currentUser.id);const box=document.getElementById("cartbox");if(error){box.textContent=error.message;await updateCartBadge();return;}await updateCartBadge();if(!data?.length){box.innerHTML="Cart empty.";return;}let itemTotal=0,mrpTotal=0;const items=data.map(x=>{const price=Number(x.products?.price||0),mrp=Number(x.products?.mrp||price),qty=Number(x.quantity||0),line=price*qty;itemTotal+=line;mrpTotal+=Math.max(price,mrp)*qty;return{x,price,mrp,qty,line};});const productDiscount=Math.max(0,mrpTotal-itemTotal);const sellerGroups={};items.forEach(it=>{const s=it.x.products?.Sellers?.shop_name||it.x.products?.Sellers?.seller_name||"Marketplace Seller";(sellerGroups[s]||(sellerGroups[s]=[])).push(it);});const groupedHtml=Object.entries(sellerGroups).map(([seller,group])=>'<div class="panel"><h3>🏪 '+esc(seller)+'</h3>'+group.map(({x,price,mrp,qty,line})=>`<div class="panel row"><img src="${x.products?.image_url||"https://placehold.co/120x90?text=ShubhMart"}" style="width:90px;height:70px;object-fit:cover;border-radius:10px"><div style="flex:1;min-width:160px"><b>${esc(x.products?.name||"Product")}</b><div class="small">${esc(x.products?.category||"")}</div><div><b>₹${price.toFixed(2)}</b> ${mrp>price?'<span class="old"> ₹'+mrp.toFixed(2)+'</span>':''} × ${qty}</div><div><b>Item Total: ₹${line.toFixed(2)}</b></div></div><div><button class="btn" onclick="changeQty('${x.id}',${qty-1})">−</button><button class="btn" onclick="changeQty('${x.id}',${qty+1})">+</button><button class="btn alt" onclick="removeCart('${x.id}')">Remove</button></div></div>`).join("")+'</div>').join("");box.innerHTML='<h3>Added Products</h3>'+groupedHtml+async function validateCheckoutServer(couponCode="",deliveryMethod="standard"){if(!currentUser)return{valid:false,message:"Login required"};const r=await sb.rpc("validate_checkout_cart",{p_customer_id:currentUser.id,p_coupon_code:String(couponCode||""),p_delivery_method:String(deliveryMethod||"standard")});if(r.error){note("Checkout validation error: "+r.error.message,true);return{valid:false,message:r.error.message};}const x=r.data?.[0];if(x&&!x.valid)note(x.message||"Checkout validation failed",true);return x||{valid:false,message:"Checkout validation failed"};}

