const sb=window.shubhSupabase;let user=null,partner=null;
function note(t,b){const e=document.getElementById("msg");e.className="msg "+(b?"danger":"ok");e.textContent=t}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function deliveryRegister(){const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value,name=document.getElementById("name").value.trim(),phone=document.getElementById("phone").value.trim(),vehicle=document.getElementById("vehicle").value.trim(),vehicleNo=document.getElementById("vehicleNo").value.trim();if(!email||!password||!name||!phone)return note("Name, mobile, email aur password zaroor bhariye.",true);localStorage.setItem("shubhmart_delivery_draft",JSON.stringify({name,phone,vehicle,vehicleNo}));const r=await sb.auth.signUp({email,password});if(r.error)return note(r.error.message,true);if(r.data.session)await finish(r.data.user);else note("Registration ho gaya. Email verify karke Login kijiye.")}
async function finish(u){const d=JSON.parse(localStorage.getItem("shubhmart_delivery_draft")||"{}");let r=await sb.from("delivery_partners").upsert({user_id:u.id,name:d.name||"",phone:d.phone||"",email:u.email||"",vehicle_type:d.vehicle||"",vehicle_number:d.vehicleNo||"",status:"Pending",availability:"Offline"},{onConflict:"user_id"}).select().single();if(r.error)return note(r.error.message,true);partner=r.data;user=u;localStorage.removeItem("shubhmart_delivery_draft");showDash()}
async function deliveryLogin(){const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value;if(!email||!password)return note("Email aur password bhariye.",true);const r=await sb.auth.signInWithPassword({email,password});if(r.error)return note(r.error.message,true);const q=await sb.from("delivery_partners").select("*").eq("user_id",r.data.user.id).maybeSingle();if(q.error)return note(q.error.message,true);if(!q.data){return note("Delivery profile nahi mila. Register kijiye.",true)}user=r.data.user;partner=q.data;showDash()}
function showDash(){document.getElementById("auth").classList.add("hidden");document.getElementById("dash").classList.remove("hidden");document.getElementById("logout").classList.remove("hidden");document.getElementById("title").textContent=(partner.name||"Delivery Partner")+" — Dashboard";document.getElementById("partnerStatus").textContent="Account: "+partner.status+" | Availability: "+partner.availability;loadShipments()}
async function toggleAvailability(){if(partner.status!=="Approved")return note("Admin approval ke baad online ho sakte hain.",true);const next=partner.availability==="Online"?"Offline":"Online";const r=await sb.from("delivery_partners").update({availability:next,updated_at:new Date().toISOString()}).eq("id",partner.id);if(r.error)return note(r.error.message,true);partner.availability=next;showDash()}
const statuses=["Assigned","Picked Up","Packed","Dispatched","Out for Delivery","Delivered","Failed","RTO","Return Pickup","Returned"];
async function updateShipment(id,status){const patch={shipment_status:status,updated_at:new Date().toISOString()};const now=new Date().toISOString();if(status==="Picked Up")patch.picked_up_at=now;if(status==="Dispatched")patch.dispatched_at=now;if(status==="Out for Delivery")patch.out_for_delivery_at=now;if(status==="Delivered")patch.delivered_at=now;const r=await sb.from("shipments").update(patch).eq("id",id).eq("delivery_partner_id",partner.id);if(r.error)return note(r.error.message,true);const ev=await sb.from("delivery_events").insert({shipment_id:id,status,note:"Updated by delivery partner",actor_user_id:user.id});if(ev.error)return note(ev.error.message,true);await loadShipments();note("Shipment status updated.")}
async function loadShipments(){const e=document.getElementById("shipments");const r=await sb.from("shipments").select("id,order_id,tracking_number,shipment_status,delivery_method,estimated_delivery_at,created_at").eq("delivery_partner_id",partner.id).order("created_at",{ascending:false});if(r.error)return e.textContent=r.error.message;if(!r.data?.length)return e.innerHTML="<div class='card'>Abhi koi shipment assigned nahi hai.</div>";e.innerHTML=r.data.map(s=>"<div class='card'><b>Order #"+esc(s.order_id.slice(0,8))+"…</b><br>Tracking: "+esc(s.tracking_number||"Not assigned")+"<br>Status: <b>"+esc(s.shipment_status)+"</b><br>"+(s.estimated_delivery_at?"ETA: "+esc(new Date(s.estimated_delivery_at).toLocaleString("en-IN")):"")+(s.shipment_status!=="Delivered"&&s.shipment_status!=="Cancelled"?"<br><select onchange="updateShipment('"+s.id+"',this.value)"><option value=''>Update status…</option>"+statuses.map(x=>"<option>"+x+"</option>").join("")+"</select>":"")+"</div>").join("")}
async function deliveryLogout(){await sb.auth.signOut();location.reload()}
sb.auth.onAuthStateChange((e,s)=>{if(s&&!user)setTimeout(()=>{deliveryLogin().catch(()=>{})},0)});
